---
title: "Procesamientos Jornadas de sociología UNLP 2024"
format: 
  html:
    theme: journal
    toc: true
    code-fold: show
execute:
  echo: false
  warning: false
  message: false
---

## Librerías y bases
```{r }
rm(list = ls())

pacman::p_load(tidyverse, Hmisc, gtsummary, GDAtools, jtools, huxtable, survey, ggoxford, ggtext, factoextra, paletteer)

load("bases/latinobarometro_select.RData")
load("bases/ingresos_tributarios_wb_tot.RData")
load("bases/base_datos_agregados.RData")

ingresos_tributarios_wb_tot <- ingresos_tributarios_wb_tot %>% 
  rename(iso3 = pais)

theme_set(theme_bw())

```


## Arreglos de variables

```{r variables}
latinobarometro <- latinobarometro %>% 
  mutate(arreglo_impuestos = ifelse(arreglo_impuestos == 2, 0, 1),
         evasion_dic = ifelse(evasion == 1, 1, 0),
         evasion_dic2 = ifelse(evasion == 1, 0, 1),
         evasion_dic3 = ifelse(evasion >= 7, 1, 0),
         argentina_lat = case_when(pais == 32 ~ "Argentina",
                                   TRUE ~ "Resto América Latina"),
         pro_mercado_dic = factor(case_when(pro_mercado_f == "Muy de acuerdo" ~ "De acuerdo",
                                            pro_mercado_f == "De acuerdo" ~ "De acuerdo",
                                            pro_mercado_f == "En desacuerdo" ~ "En desacuerdo",
                                            pro_mercado_f == "Muy en desacuerdo" ~ "En desacuerdo",
                                            TRUE ~ NA_character_))) %>% 
  filter(pais_f != "Esp")


#Banderas
latinobarometro <- latinobarometro %>% 
  mutate(iso3 = countrycode::countrycode(pais,
                                         origin = "iso3n",
                                         destination = "iso3c"),
         anio_pais = interaction(iso3, anio))

#Unión
latinobarometro <- latinobarometro %>% 
  left_join(ingresos_tributarios_wb_tot, by = c("anio", "iso3"))

#Unión bases individual y agregada
latinobarometro <- latinobarometro %>% 
  left_join(datos_paises, by = c("anio", "iso3")) 

latinobarometro <- latinobarometro %>% 
  mutate(anio_pais = interaction(iso3, anio))

latinobarometro$pib_ppa_log <- log(latinobarometro$pib_ppa)

```


## Construcción de índice de estratificación con ACM
```{r ACM}
latinobarometro <- latinobarometro %>%  
  mutate(trabajo_f = case_when(
    estado_ocupacional_f %in% c("Temporalmente no trabaja", "Retirado/pensionado") ~ trabajo_anterior_f, 
                               estado_ocupacional_f %in% c("No trabaja", "Estudiante") ~ "No trabaja",
         TRUE ~ trabajo_actual_f))


#2020
var_obj_2020 <- latinobarometro %>%
  filter(anio == 2020) %>%
  select(trabajo_f, nivel_ed, bienes_comp, bienes_lava, bienes_telef, bienes_celular, bienes_auto, bienes_cloaca, bienes_aguapot,
         bienes_aguacal, bienes_casa, wt)

mca2020 <- speMCA(var_obj_2020[,1:11], ncp = 2, row.w = var_obj_2020$wt)

mca2020 <- flip.mca(mca2020, dim = 1)

modif.rate(mca2020)$modif

contribuciones <- tabcontrib(mca2020, dim = 1, best = F)

openxlsx::write.xlsx(contribuciones, "graficos/evasion/contribuciones_mca_2020.xlsx")

ggcloud_variables(mca2020, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3, ) + 
  labs(title = "MCA 2020")

#Construcción de índice (estandarizado)
estandarizar_ponderado <- function(x, w) {
  media_ponderada <- sum(x * w) / sum(w)
  var_ponderada <- sum(w * (x - media_ponderada)^2) / sum(w)
  desv_ponderada <- sqrt(var_ponderada)
  return((x - media_ponderada) / desv_ponderada)
}

coords_2020 <- data.frame(anio = 2020, dim1 = mca2020$ind$coord[,1])


# Filtrar y unir con coordenadas
latinobarometro2020 <- latinobarometro %>%
  filter(anio == 2020) %>%
  bind_cols(dim1 = coords_2020$dim1) %>%
  mutate(dim1_std = estandarizar_ponderado(dim1, wt),
         dim1_01= scales::rescale(dim1, to = c(0, 1)))


latinobarometro2020 %>% 
  group_by(iso3) %>%
  summarise(
  promedio = weighted.mean(dim1_std, wt = wt, na.rm = T)) %>%
  ggplot(aes(x = fct_reorder(iso3, promedio, .desc = T), y = promedio)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  geom_segment(aes(x=iso3, xend=iso3, y=0, yend=promedio), color="orange") +
  geom_point( color="orange", size=3) +
  geom_axis_flags(breaks = latinobarometro$iso3,
                  labels = latinobarometro$pais_f,
                  country_icons = latinobarometro$iso3,
                  width = 20,
                  lineheight = 2) +
  labs(title = "Gráfico 1. Índice de estratificación social objetiva promedio",
       subtitle = "Países seleccionados de América Latina. 2020",
       caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 11)) +
  scale_y_continuous(limits = c(-1, 1), breaks = seq(-1, 1, .5))

ggsave("graficos/evasion/estratificacion_objetiva.png", width = 7, height = 5, dpi = 300)

```
## Datos descriptivos

```{r descriptivos impuestos}

# prom_gap <- latinobarometro %>% 
#   filter(!iso3 %in% c("BOL", "COL", "VEN")) %>%
#   summarise(gap = mean(gap, na.rm = T))
# 
# latinobarometro %>% 
#   filter(!iso3 %in% c("BOL", "COL", "VEN"), anio <= 2020) %>% 
#   group_by(anio, iso3) %>% 
#   summarise(gap_pais = mean(gap, na.rm = T)) %>% 
#   ggplot(aes(x = anio, y = gap_pais, group = 1)) +
#   geom_line() +
#   geom_hline(yintercept = prom_gap$gap, linetype = "dashed", color = "red") +
#   labs(
#     title = "Evolución de la diferencia entre los ingresos tributarios potenciales y efectivos",
#     subtitle = "Países seleccionados. 1998-2020. En porcentaje del PBI.",
#     caption = "Fuente: elaboración propia en base a Tax Revenue Dashboard (Banco Mundial)"
#   ) +
#   theme(
#     axis.title.x = element_blank(),
#     axis.title.y = element_blank(),
#     axis.text.x = element_text(size = 8),
#     axis.text.y = element_text(size = 9),
#     strip.text = element_text(size = 8, margin = margin(t = 2, b = 2))
#   ) +
#   facet_wrap(~iso3, ncol = 4)


prom_evasion <- latinobarometro %>% 
  summarise(evasion = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T))          

latinobarometro %>% 
  group_by(anio, iso3) %>% 
  summarise(evasion = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T)) %>%
  na.omit() %>% 
  ggplot(aes(x = anio, y = evasion, group = 1)) +
  # geom_line(na.rm = T) +
  geom_hline(yintercept = prom_evasion$evasion, linetype = "dashed", color = "red", size = .4) +
  geom_point(size = 1) +
  geom_text(
    data = function(d) d %>% filter(anio == 2020),
    aes(label = scales::percent(evasion, accuracy = 1)),
    size = 2.5, vjust = -0.8,hjust = 1
  ) +
  labs(
    title = "Gráfico 3. Evolución del porcentaje de personas que conoce a alguien \nque pagó menos impuestos del que debían",
    subtitle = "Países seleccionados. 1998-2020 (Promedio general en línea punteada roja).",
    caption = "Fuente: elaboración propia en base a Latinobarómetro"
  ) + 
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 6.5),
    axis.text.y = element_text(size = 8),
    strip.text = element_text(size = 8, margin = margin(t = 2, b = 2))
  ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1, suffix = ""), breaks = seq(0, .5, 0.15), limits = c(0, .5)) +
  scale_x_continuous(breaks = seq(1998, 2020, 2), limits = c(1998, 2020)) +
  facet_wrap(~iso3, ncol = 3)


ggsave("graficos/evasion/porcentaje_evasion_impuestos.png", width = 6, height = 5, dpi = 300)

```

```{r evasión 2020 países, eval=FALSE}
latinobarometro %>% 
  filter(anio == 2020) %>%
  group_by(iso3) %>%
  summarise(
    promedio = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T)) %>% 
  filter(!is.na(promedio)) %>% 
  ggplot(aes(x = fct_reorder(iso3, promedio, .desc = T), y = promedio, fill = iso3)) +
  geom_bar(stat = "identity", alpha = .8) +
  geom_text(aes(label = scales::percent(promedio, accuracy = 0.1, 
                                        suffix = "")),
            position = position_stack(.95),
            size = 2.5) +
  geom_axis_flags(breaks = latinobarometro$iso3,
                  labels = latinobarometro$pais_f,
                  country_icons = latinobarometro$iso3,
                  width = 20,
                  lineheight = 2) +
  labs(title = "Gráfico 2. Porcentaje de personas que conoce a alguien que pagó menos \nimpuestos de lo que debía",
       subtitle = "Países de América Latina. 2020",
       caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, .4, 0.05), limits = c(0, .4)) +
  scale_fill_manual(values = ifelse(levels(latinobarometro$pais_f) == "Arg", "red", "grey")) 

ggsave("graficos/evasion/porcentaje_evasion_impuestos_paises.png", width = 7, height = 5, dpi = 300)

```

```{r estratificación y evasión}
modelo <- latinobarometro2020 %>% 
  filter(iso3 != "CHL") %>% 
  group_by(iso3) %>% 
  summarise(
    promedio = weighted.mean(dim1_std, wt = wt, na.rm = TRUE),
    evasion = weighted.mean(arreglo_impuestos, wt = wt, na.rm = TRUE)
  ) |> 
  lm(evasion ~ promedio, data = _)

r2 <- summary(modelo)$r.squared


latinobarometro2020 %>%
  group_by(iso3) %>%
  filter(iso3 != "CHL") %>% 
  summarise(
    promedio = weighted.mean(dim1_std, wt = wt, na.rm = T),
    evasion = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T)) %>% 
  ggplot(aes(x = promedio, y = evasion)) +
  geom_point(size = 2, alpha = .5) +
  geom_smooth(method = "lm", se = TRUE, linewidth = .5, color = "red") +
  ggrepel::geom_text_repel(aes(label = iso3), size = 2.5, show.legend = FALSE) +
  annotate("text",
           x = 0.32, y = 0.39,  # Ajustá posición
           label = paste0("R² = ", round(r2, 3)),
           size = 3.5, hjust = 0) +
  labs(title = "Gráfico 4. Incumplimiento impositivo y estratificación social objetiva",
       subtitle = "Países de América Latina. 2020. Error estándar en gris.",
       caption = "Fuente: elaboración propia en base a Latinobarómetro.  
       Chile fue descartado en este gráfico ya que puede considerarse un caso *outlier*.",
       y = "Arreglo para pagar menos impuestos",
       x = "Estratificación social objetiva media de países") +
  theme(axis.title.x = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.text.x = element_text(size = 9),
        axis.text.y = element_text(size = 9),
        plot.caption = ggtext::element_markdown(size = 9)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(.15, .4, 0.05), limits = c(.15, .4)) +
  scale_x_continuous(labels = scales::number_format(accuracy = 0.1), breaks = seq(-1, 1, 0.2), limits = c(-1, 1))

ggsave("graficos/evasion/estratificacion_evasion.png", width = 7, height = 5, dpi = 300)


```

```{r evasión y clase subjetiva}
latinobarometro2020 %>%
  filter(!is.na(clase_subjetiva4)) %>% 
  group_by(iso3, clase_subjetiva4) %>%
  summarise(
    promedio = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T)) %>% 
  ggplot(aes(x = clase_subjetiva4, y = promedio)) +
  geom_bar(stat = "identity", fill = "steelblue", alpha = .8) +
  geom_hline(yintercept = prom_evasion$evasion, linetype = "dashed", color = "red") +
  labs(title = "Gráfico 5. Porcentaje de personas que conoce a alguien que pagó menos \nimpuestos de lo debían según clase social subjetiva",
       subtitle = "Países de América Latina. 2020 (Porcentaje general en línea punteada roja).",
       caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  theme(
    title = element_text(size = 10),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    strip.text = element_text(size = 8, margin = margin(t = 2, b = 2))
  ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1, suffix = ""), breaks = seq(0, .65, 0.15), limits = c(0, .65)) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 5)) +
  facet_wrap(~iso3, ncol = 3)
  
  
ggsave("graficos/evasion/porcentaje_evasion_impuestos_clase_subjetiva.png", width = 6, height = 5, dpi = 300)


latinobarometro2020 %>%
  filter(!is.na(clase_subjetiva4)) %>% 
  mutate(clase_media = ifelse(clase_subjetiva4 == "Media alta", 1, 0)) %>%
  group_by(iso3) %>%
  summarise(
    promedio = weighted.mean(arreglo_impuestos, wt = wt, na.rm = TRUE),
    porc_media = weighted.mean(clase_media, wt, na.rm = TRUE)
  ) %>% 
  ggplot(aes(x = porc_media, y = promedio)) +
  geom_point(size = 2, alpha = .5) +
  geom_smooth(method = "lm", se = TRUE, linewidth = .5, color = "red") +
  ggrepel::geom_text_repel(aes(label = iso3), size = 2.5, show.legend = FALSE)



```

## Tabla de estadísticos descriptivos

```{r descriptivos, results='asis'}
theme_gtsummary_language("es", decimal.mark = ",", big.mark = ".")
theme_gtsummary_compact()

latinobarometro2020 %>%
  svydesign(data = ., ids = ~ 1, weights = ~wt) %>%
  tbl_svysummary(include = c(edad, sexo2, dim1_std, clase_subjetiva4, just_dist_ingresos_dic, pro_mercado_dic, ayuda_pobres_dinero_f, ayuda_gobierno_tramo_f, pago_impuestos_dic, aceptabilidad_desigualdad, corrupcion_f, ideologia, arreglo_impuestos),
                 label = c(edad ~ "Edad", 
                           sexo2 ~ "Sexo", 
                           dim1_std ~ "Índice de estratificación", 
                           clase_subjetiva4 ~ "Clase subjetiva", 
                           just_dist_ingresos_dic ~ "Percepción distribución de ingresos", 
                           pro_mercado_dic ~ "Valoración economía de mercado", 
                           ayuda_pobres_dinero_f ~ "Aprueba ayuda en dinero a pobres", 
                           ayuda_gobierno_tramo_f ~ "Tramo a recibir ayuda del gob.",
                           pago_impuestos_dic ~ "Opinión pago de impuestos", 
                           aceptabilidad_desigualdad ~ "Aceptación de la desigualdad (1 inaceptable - 10 aceptable)",
                           corrupcion_f ~ "Progreso contra la corrupción",
                           ideologia ~ "Ideología (0 izqda - 10 derecha)",
                           arreglo_impuestos ~ "Arreglo para pagar menos impuestos"),
                 statistic = list(all_continuous() ~ "{mean} ({sd})",
                                  all_categorical() ~ "{n} ({p}%)"),
                 digits = list(all_categorical() ~ c(0, 1)),
                 missing = "no") %>% 
  as_flex_table() %>% 
  flextable::save_as_docx(path = "graficos/evasion/descriptivos_2020.docx")

latinobarometro2020 %>%
  svydesign(data = ., ids = ~ 1, weights = ~wt) %>%
  tbl_svysummary(include = c(edad, sexo2, dim1_std, clase_subjetiva4, just_dist_ingresos_dic, pro_mercado_dic, ayuda_pobres_dinero_f, ayuda_gobierno_tramo_f, pago_impuestos_dic, aceptabilidad_desigualdad, corrupcion_f, ideologia, arreglo_impuestos),
                 label = c(edad ~ "Edad", 
                           sexo2 ~ "Sexo", 
                           dim1_std ~ "Índice de estratificación", 
                           clase_subjetiva4 ~ "Clase subjetiva", 
                           just_dist_ingresos_dic ~ "Percepción distribución de ingresos", 
                           pro_mercado_dic ~ "Valoración economía de mercado", 
                           ayuda_pobres_dinero_f ~ "Aprueba ayuda en dinero a pobres", 
                           ayuda_gobierno_tramo_f ~ "Tramo a recibir ayuda del gob.",
                           pago_impuestos_dic ~ "Opinión pago de impuestos", 
                           aceptabilidad_desigualdad ~ "Aceptación de la desigualdad (1 inaceptable - 10 aceptable)",
                           corrupcion_f ~ "Progreso contra la corrupción",
                           ideologia ~ "Ideología (1 izqda - 10 derecha)",
                           arreglo_impuestos ~ "Arreglo para pagar menos impuestos"),
                 statistic = list(all_continuous() ~ "{mean} ({sd})",
                                  all_categorical() ~ "{n} ({p}%)"),
                 digits = list(all_categorical() ~ c(0, 1)),
                 missing = "no")  %>%  
as_gt()
  

```



## Regresiones (efectos fijos por país)

```{r regresion}

latinobarometro2020$just_dist_ingresos_dic <- relevel(latinobarometro2020$just_dist_ingresos_dic, ref = "Muy justa-justa-injusta")
latinobarometro2020$clase_subjetiva4 <- relevel(latinobarometro2020$clase_subjetiva4, ref = "Baja")
latinobarometro2020$pro_mercado_dic <- relevel(latinobarometro2020$pro_mercado_dic, ref = "De acuerdo")
latinobarometro2020$pais_f <- relevel(latinobarometro2020$pais_f, ref = "Mex")
latinobarometro2020$sexo2 <- relevel(latinobarometro2020$sexo2, ref = "Mujer")
latinobarometro2020$ayuda_pobres_dinero_f <- relevel(latinobarometro2020$ayuda_pobres_dinero_f, ref = "No")
latinobarometro2020$ayuda_gobierno_tramo_f <- relevel(latinobarometro2020$ayuda_gobierno_tramo_f, ref = "A ninguno")
# latinobarometro2020$pago_impuestos_tramo_f <- relevel(latinobarometro2020$pago_impuestos_tramo_f, ref = "Ninguno")
# latinobarometro2020$corrupcion_f <- relevel(latinobarometro2020$corrupcion_f, ref = "Nada")

latinobarometro2020$arreglo_impuestos <- as.factor(latinobarometro2020$arreglo_impuestos)

latinobarometro2020$edad2 <- latinobarometro2020$edad^2

mod2_a <- glm(arreglo_impuestos ~ edad + edad2 + sexo2 + dim1_std + clase_subjetiva4,
                 data = latinobarometro2020, weights = wt, family = binomial(link = "logit"))

mod2_b <- glm(arreglo_impuestos ~ edad + edad2 + sexo2 + dim1_std + clase_subjetiva4 + just_dist_ingresos_dic + pro_mercado_dic + ayuda_pobres_dinero_f + ayuda_gobierno_tramo_f + pago_impuestos_dic + aceptabilidad_desigualdad + corrupcion_f + ideologia, data = latinobarometro2020, weights = wt, family = binomial(link = "logit"))

mod2_c <- glm(arreglo_impuestos ~ edad + edad2 + sexo2 + dim1_std + clase_subjetiva4 + just_dist_ingresos_dic + pro_mercado_dic + ayuda_pobres_dinero_f + ayuda_gobierno_tramo_f + pago_impuestos_dic + aceptabilidad_desigualdad + corrupcion_f + ideologia + pais_f, data = latinobarometro2020, weights = wt, family = binomial(link = "logit"), na.action = na.exclude)

mod3 <- glm(arreglo_impuestos ~ edad + edad2 + sexo2 + dim1_std + clase_subjetiva4 + just_dist_ingresos_dic + pro_mercado_dic + ayuda_pobres_dinero_f + ayuda_gobierno_tramo_f + pago_impuestos_dic + aceptabilidad_desigualdad + corrupcion_f + ideologia, data = subset(latinobarometro2020, iso3 == "ARG"), weights = wt, family = binomial(link = "logit"), na.action = na.exclude)


mod1 <- export_summs(mod2_a, mod2_b, mod2_c, mod3, model.names = c("Variables estratificación", "Estratificación + mediadoras", "Efecto fijo países", "Sólo Argentina"), 
                     exp = T, stars = c(`***` = 0.01, `**` = 0.05, `*` = 0.1),
                     error_pos = "same",
                     coefs = c("Edad" = "edad",
                               "Edad2" = "edad2",
                               "Varón" = "sexo2Varón",
                               "Estratificación objetiva" = "dim1_std",
                               "Clase sub. media alta" = "clase_subjetiva4Media alta",
                               "Clase sub. media" = "clase_subjetiva4Media",
                               "Clase sub. media baja" = "clase_subjetiva4Media baja",
                               "Distribución muy injusta" = "just_dist_ingresos_dicMuy injusta",
                               "En desacuerdo mercado" = "pro_mercado_dicEn desacuerdo",
                               "Ayudar con dinero a pobres" = "ayuda_pobres_dinero_fSi",
                               "Ayuda gob. tramo bajo (ref: A ninguno)" = "ayuda_gobierno_tramo_fBajo",
                               "Ayuda gob. tramo medio" = "ayuda_gobierno_tramo_fMedio",
                               "Ayuda gob. tramo alto" = "ayuda_gobierno_tramo_fAlto",
                               "Ayuda gob. a todos" = "ayuda_gobierno_tramo_fA todos por igual",
                               "Todos deben pagar impuestos por igual (ref: solo ricos)" = "pago_impuestos_dicTodos pagan por igual",
                               "Aceptabilidad de la desigualdad" = "aceptabilidad_desigualdad",
                               "Ningún progreso contra corrupción" = "corrupcion_fNada",
                               "Ideologia (izq-der)" = "ideologia"))

mod1 %>%  
  set_caption("Modelos de regresión logística. Odds ratios. Evasión impositiva. 2020")

mod1 <- mod1 %>% 
  as_flextable() %>%  
  flextable::save_as_docx(path = "graficos/evasion/regresion.docx")
  




# reg_coef <- plot_summs(mod2_c, mod3, ci_level = 0.91,
#                        model.names = c("Efectos fijos países", "Sólo Argentina"),
#                        point.size = 2,
#                        line.size = c(0.5, 1),
#                        exp = T,
#                        coefs = c("Edad" = "edad",
#                                "Edad2" = "edad2",
#                                "Varón" = "sexo2Varón",
#                                "Estratificación objetiva" = "dim1_std",
#                                "Clase sub. media alta" = "clase_subjetiva4Media alta",
#                                "Clase sub. media" = "clase_subjetiva4Media",
#                                "Clase sub. media baja" = "clase_subjetiva4Media baja",
#                                "Distribución muy injusta" = "just_dist_ingresos_dicMuy injusta",
#                                "En desacuerdo mercado" = "pro_mercado_dicEn desacuerdo",
#                                "Ayudar con dinero a pobres" = "ayuda_pobres_dinero_fSi",
#                                "Ayuda gob. tramo bajo (ref: A ninguno)" = "ayuda_gobierno_tramo_fBajo",
#                                "Ayuda gob. tramo medio" = "ayuda_gobierno_tramo_fMedio",
#                                "Ayuda gob. tramo alto" = "ayuda_gobierno_tramo_fAlto",
#                                "Ayuda gob. a todos" = "ayuda_gobierno_tramo_fA todos por igual",
#                                "Todos deben pagar impuestos por igual (ref: solo ricos)" = "pago_impuestos_dicTodos pagan por igual",
#                                "Aceptabilidad de la desigualdad" = "aceptabilidad_desigualdad",
#                                "Ningún progreso contra corrupción" = "corrupcion_fNada",
#                                "Ideologia (izq-der)" = "ideologia"))
# 
# reg_coef +
#   labs(title ="Modelos de regresión logística. \nArreglo para pagar menos impuestos. 2020",
#        subtitle ="Coeficientes exponenciados",
#        caption = "Fuente: elaboración propia en base a Latinobarómetro",
#        x = "Razones de momios") +
#   theme(axis.title.y = element_blank(),
#         axis.title.x = element_blank(),
#         axis.text.x = element_text(size = 8),
#         axis.text.y = element_text(size = 8),
#         legend.position= "bottom",
#         legend.title = element_blank())


```

```{r Probabilidades, eval=FALSE}
library(marginaleffects)
library(ggeffects)

ame_pais <- avg_slopes(mod2_c, variables = "dim1_std", by = "pais_f")

ggplot(ame_pais, aes(x = reorder(pais_f, estimate), y = estimate)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +
  labs(
    x = "País",
    y = "AME de 'dim1_std' sobre acuerdo con arreglo de impuestos",
    title = "Efecto marginal promedio por país",
    subtitle = "Modelo sin interacción: pendiente común, efectos evaluados por país"
  ) +
  theme_minimal()


mod2_interac_a <- glm(arreglo_impuestos ~ edad + edad2 + sexo2 + clase_subjetiva4 + just_dist_ingresos_dic + pro_mercado_dic + ayuda_pobres_dinero_f + ayuda_gobierno_tramo_f + pago_impuestos_dic + aceptabilidad_desigualdad + corrupcion_f + ideologia + pais_f * dim1_std, data = latinobarometro2020, weights = wt, family = binomial(link = "logit"), , na.action = na.exclude)

ame_pais <- avg_slopes(mod2_interac_a, variables = "dim1_std", by = "pais_f")

ame_pais$signif <- ame_pais$p.value < 0.05

ggplot(ame_pais, aes(x = reorder(pais_f, estimate), y = estimate, color = signif)) +
  geom_point(size = 2) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray40") +
  coord_flip() +
  labs(
    x = "País",
    y = "Efecto marginal (AME) de la estratificación",
    title = "Efecto de la estratificación sobre la evasión por país",
    subtitle = "Colores indican significancia estadística (p < 0.05)"
  ) +
  scale_color_manual(values = c("TRUE" = "darkblue", "FALSE" = "gray60")) +
  theme_minimal(base_size = 13) +
  theme(legend.position = "none")

mod2_interac_b <- glm(arreglo_impuestos ~ edad + edad2 + sexo2 + dim1_std + clase_subjetiva4 * pais_f + just_dist_ingresos_dic + pro_mercado_dic + ayuda_pobres_dinero_f + ayuda_gobierno_tramo_f + pago_impuestos_dic + aceptabilidad_desigualdad + corrupcion_f + ideologia, data = latinobarometro2020, weights = wt, family = binomial(link = "logit"), na.action = na.exclude)

ame_pais_clase <- avg_slopes(mod2_interac_b, variables = "clase_subjetiva4", by = "pais_f")



# Agrupar por clase_subjetiva4 antes de resumir
ame_pais_clase_grouped <- ame_pais_clase %>%
  group_by(contrast) %>%
  summarize(
    mean_estimate = mean(Estimate, na.rm = TRUE),
    lower_ci = mean(`2.5 %`, na.rm = TRUE),
    upper_ci = mean(`97.5 %`, na.rm = TRUE)
  )

# Visualizar el gráfico de barras de los efectos promedio por clase subjetiva
library(ggplot2)
ggplot(ame_pais_clase_grouped, aes(x = clase_subjetiva4, y = mean_estimate, fill = mean_estimate > 0)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = 0.2) +
  labs(
    title = "Efectos promedio de clase subjetiva en la evasión fiscal",
    x = "Clase Subjetiva", y = "AME promedio (dY/dX)",
    fill = "Efecto positivo"
  ) +
  theme_minimal()


```




```{r Probabilidades estimadas}
library(ggeffects)

pred_estatus <- ggpredict(mod2_c, terms = c("dim1_std[-2, -1, 0, 1, 2]", "pais_f"),
                          typical = c(numeric = "mean", factor = "mode"))

avg_pred <- mean(pred_estatus$predicted)

estatus_labs <- c("Muy bajo (-2)", "Bajo (-1)", "Medio (0)", "Alto (1)", "Muy alto (2)")
names(estatus_labs) <- c("-2", "-1", "0", "1", "2")


pred_estatus %>% 
  ggplot(aes(x = predicted, y = reorder(group, predicted))) +
  geom_vline(xintercept = avg_pred, linetype = "dashed", color = "red") +
  geom_point(position = position_dodge(width = 0.6)) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                 height = 0.2, position = position_dodge(width = 0.6)) +
  facet_wrap(~x, labeller = labeller(x = estatus_labs), ncol = 5) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(
    title = "Gráfico 6. Probabilidad de incumplimiento impositivo según estatus objetivo",
    subtitle = "Promedio general en línea punteada roja.",
    caption = "Fuente: elaboración propia en base a Latinobarómetro. \nVariables de control mantenidas en promedio (cuantitativas) y en su moda (cualitativas)."
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    strip.text = element_text(face = "bold")
  ) 

ggsave("graficos/evasion/prediccion_estatus_objetivo.png", width = 8, height = 5, dpi = 300)



pred_clase <- ggpredict(mod2_c, terms = c("clase_subjetiva4", "pais_f"),
                        typical = c(numeric = "mean", factor = "mode"))

pred_clase$x <- factor(pred_clase$x, levels = c("Baja", "Media baja", "Media", "Media alta"))

avg_pred <- mean(pred_clase$predicted)

pred_clase %>% 
  ggplot(aes(x = predicted, y = reorder(group, predicted))) +
  geom_vline(xintercept = avg_pred, linetype = "dashed", color = "red") +
  geom_point(position = position_dodge(width = 0.6)) +
  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high),
                 height = 0.2, position = position_dodge(width = 0.6)) +
  facet_wrap(~x, nrow = 1) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_color_paletteer_d("PNWColors::Sunset2") +
  labs(
    title = "Gráfico 7. Probabilidad de incumplimiento impositivo según clase subjetiva",
    subtitle = "Promedio general en línea punteada roja.",
    color = "Clase subjetiva",
    caption = "Fuente: elaboración propia en base a Latinobarómetro. \nVariables de control mantenidas en promedio (cuantitativas) y en su moda (cualitativas)."
  ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "bottom",
    strip.text = element_text(face = "bold")
  )

ggsave("graficos/evasion/prediccion_clase_subjetiva.png", width = 8, height = 5, dpi = 300)

```
# Anexo

```{r Anexo}
latinobarometro %>% 
  filter(anio == 2020 | anio == 2010, !iso3 %in% c("VEN", "NIC")) %>%
  group_by(anio_pais) %>%
  summarise(
    impuestos = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T),
    pib_ppa = mean(pib_ppa, na.rm = T)) %>% 
  ggplot(aes(x = pib_ppa, y = impuestos)) +
  geom_point() +
  geom_smooth(method = "lm", se = T, color = "red") +
  ggpmisc::stat_poly_eq(
    formula = y ~ x,  # Fórmula del modelo lineal
    aes(label = paste(after_stat(rr.label), sep = "*\", \"*")),  # Mostrar R²
    parse = TRUE,
    label.x = "right",  # Posición de la leyenda
    size = 4
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 2.5) +
  labs(title = "Gráfico 8. Incumplimiento impositivo y PIB per cápita",
       subtitle = "Países de América Latina. 2010 y 2020",
       caption = "Fuente: elaboración propia en base a Latinobarómetro y World Development Indicators (Banco Mundial)",
       y = "% de incumplimiento impositivo",
       x = "PIB per cápita (U$S PPA)") +
  scale_x_continuous(labels = scales::dollar_format(accuracy = 1, prefix = "$"), 
                     breaks = seq(5000, 30000, 5000), limits = c(5000, 30000)) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, .4, 0.05), limits = c(0, .4))

ggsave("graficos/evasion/evasion_pib.png", width = 8, height = 5)

latinobarometro %>% 
  filter(anio == 2020 | anio == 2010, !iso3 %in% c("VEN", "NIC")) %>%
  group_by(anio_pais) %>%
  summarise(
    impuestos = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T),
    gini = mean(gini, na.rm = T)) %>% 
  ggplot(aes(x = gini, y = impuestos)) +
  geom_point() +
  geom_smooth(method = "lm", se = T, color = "red") +
    ggpmisc::stat_poly_eq(
    formula = y ~ x,  # Fórmula del modelo lineal
    aes(label = paste(after_stat(rr.label), sep = "*\", \"*")),  # Mostrar R²
    parse = TRUE,
    label.x = "right",  # Posición de la leyenda
    size = 4
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 2.5) +
  labs(title = "Gráfico 9. Incumplimiento impositivo e índice de Gini",
       subtitle = "Países de América Latina. 2010 y 2020",
       caption = "Fuente: elaboración propia en base a Latinobarómetro y CEPAL",
       y = "% de incumplimiento impositivo",
       x = "Índice de Gini") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, .4, 0.05), limits = c(0, .4))

ggsave("graficos/evasion/evasion_gini.png", width = 8, height = 5)


latinobarometro %>% 
  filter(anio == 2020 | anio == 2010, !iso3 %in% c("VEN", "NIC")) %>%
  group_by(anio_pais) %>%
  summarise(
    impuestos_ind = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T),
    impuestos_pbi = mean(impuestos_tot, na.rm = T)) %>% 
  ggplot(aes(x = impuestos_pbi, y = impuestos_ind)) +
  geom_point() +
  geom_smooth(method = "lm", se = T, color = "red") +
    ggpmisc::stat_poly_eq(
    formula = y ~ x,  # Fórmula del modelo lineal
    aes(label = paste(after_stat(rr.label), sep = "*\", \"*")),  # Mostrar R²
    parse = TRUE,
    label.x = "right",  # Posición de la leyenda
    size = 4
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 2.5) +
  labs(title = "Gráfico 10. Incumplimiento impositivo y % ingresos fiscales / PIB",
       subtitle = "Países de América Latina. 2010 y 2020",
       caption = "Fuente: elaboración propia en base a Latinobarómetro y Tax Revenue Dashboard (Banco Mundial)",
       y = "% de incumplimiento impositivo",
       x = "Ingresos fiscales / PIB") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, .4, 0.05), limits = c(0, .4))

ggsave("graficos/evasion/evasion_impuestos_pbi.png", width = 8, height = 5)


latinobarometro %>% 
  filter(anio == 2020 | anio == 2010, !iso3 %in% c("VEN", "NIC")) %>%
  group_by(anio_pais) %>%
  summarise(
    impuestos = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T),
    informalidad = mean(informalidad, na.rm = T)) %>% 
  ggplot(aes(x = informalidad, y = impuestos)) +
  geom_point() +
  geom_smooth(method = "lm", se = T, color = "red") +
    ggpmisc::stat_poly_eq(
    formula = y ~ x,  # Fórmula del modelo lineal
    aes(label = paste(after_stat(rr.label), sep = "*\", \"*")),  # Mostrar R²
    parse = TRUE,
    label.x = "right",  # Posición de la leyenda
    size = 4
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 2.5) +
  labs(title = "Gráfico 11. Incumplimiento impositivo y % de informalidad laboral",
       subtitle = "Países de América Latina. 2010 y 2020",
       caption = "Fuente: elaboración propia en base a Latinobarómetro e ILOStat",
       y = "% de incumplimiento impositivo",
       x = "% de informalidad") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, .4, 0.05), limits = c(0, .4))

ggsave("graficos/evasion/evasion_informalidad.png", width = 8, height = 5)

latinobarometro %>% 
  filter(anio == 2020 | anio == 2010, !iso3 %in% c("VEN", "NIC")) %>%
  group_by(anio_pais) %>%
  summarise(
    impuestos = weighted.mean(arreglo_impuestos, wt = wt, na.rm = T),
    ocupaciones_medias = mean(ocupaciones_medias, na.rm = T)) %>% 
  ggplot(aes(x = ocupaciones_medias, y = impuestos)) +
  geom_point() +
  geom_smooth(method = "lm", se = T, color = "red") +
    ggpmisc::stat_poly_eq(
    formula = y ~ x,  # Fórmula del modelo lineal
    aes(label = paste(after_stat(rr.label), sep = "*\", \"*")),  # Mostrar R²
    parse = TRUE,
    label.x = "right",  # Posición de la leyenda
    size = 4
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 2.5) +
  labs(title = "Gráfico 12. Incumplimiento impositivo y % de clases medias",
       subtitle = "Países de América Latina. 2010 y 2020",
       caption = "Fuente: elaboración propia en base a Latinobarómetro, CEPAL e ILOStat",
       y = "% de incumplimiento impositivo",
       x = "% de clases medias") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, .4, 0.05), limits = c(0, .4))

ggsave("graficos/evasion/evasion_clases_medias.png", width = 8, height = 5)



```

