---
title: "Clase subjetiva en América Latina"
format: 
  html:
    theme: journal
    toc: true
    code-fold: show
execute:
  echo: true
  warning: false
  message: false
cache: true
---

# Carga de librerías y bases

```{r Carga librerías y bases}
rm(list = ls())

pacman::p_load(tidyverse, Hmisc, gtsummary, GDAtools, jtools, huxtable, survey, ggoxford, ggtext, lme4, performance, sjPlot, ggsci, flextable)

theme_set(theme_light())

load("bases/latinobarometro_select.RData")
load("bases/base_datos_agregados.RData")

#id único
latinobarometro <- latinobarometro %>%
  group_by(pais, anio) %>%
  mutate(id_fila = paste0(pais, anio, row_number())) %>%
  ungroup()


#Banderas
latinobarometro <- latinobarometro  %>%  
  mutate(iso3 = countrycode::countrycode(pais,
                                         origin = "iso3n",
                                         destination = "iso3c"))

#Unión bases individual y agregada
latinobarometro <- latinobarometro %>% 
  left_join(datos_paises, by = c("anio", "iso3")) 

latinobarometro <- latinobarometro %>% 
  mutate(anio_pais = interaction(iso3, anio))

latinobarometro_sel <- latinobarometro %>% 
  filter(anio %in% c(2011, 2013, 2015, 2017, 2018, 2020, 2023, 2024), !iso3 %in% c("ESP", "VEN", "NIC"))

rm(latinobarometro, datos_paises)
```

# Pre-procesamiento de datos

## Construcción de estatus objetivo (ACM)
```{r Construcción estatus objetivo}
latinobarometro_sel <- latinobarometro_sel %>% 
  mutate(trabajo_f = case_when(
    estado_ocupacional_f %in% c("Temporalmente no trabaja", "Retirado/pensionado") ~ trabajo_anterior_f, 
                               estado_ocupacional_f %in% c("No trabaja", "Estudiante") ~ "No trabaja",
         TRUE ~ trabajo_actual_f))

# Construcción de variables para el MCA ----------------


#2011
var_obj_2011 <- latinobarometro_sel %>%
  filter(anio == 2011) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2011 <- speMCA(var_obj_2011[,1:8], ncp = 2, row.w = var_obj_2011$wt)

modif.rate(mca2011)$modif

mca2011 <- flip.mca(mca2011, dim = 1)

ggcloud_variables(mca2011, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3, ) + 
  labs(title = "MCA 2011")

#2013
var_obj_2013 <- latinobarometro_sel %>%
  filter(anio == 2013) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2013 <- speMCA(var_obj_2013[,1:8], ncp = 2, row.w = var_obj_2013$wt)

modif.rate(mca2013)$modif

mca2013 <- flip.mca(mca2013, dim = 1)

ggcloud_variables(mca2013, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3) + 
  labs(title = "MCA 2013")

#2015
var_obj_2015 <- latinobarometro_sel %>%
  filter(anio == 2015) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2015 <- speMCA(var_obj_2015[,1:8], ncp = 2, row.w = var_obj_2015$wt)

modif.rate(mca2015)$modif

mca2015 <- flip.mca(mca2015, dim = 1)

ggcloud_variables(mca2015, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3) +
  labs(title = "MCA 2015")

#2017
var_obj_2017 <- latinobarometro_sel %>%
  filter(anio == 2017) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2017 <- speMCA(var_obj_2017[,1:8], ncp = 2, row.w = var_obj_2017$wt)

modif.rate(mca2017)$modif

mca2017 <- flip.mca(mca2017, dim = 1)

ggcloud_variables(mca2017, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3) + 
  labs(title = "MCA 2017")

#2018
var_obj_2018 <- latinobarometro_sel %>%
  filter(anio == 2018) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2018 <- speMCA(var_obj_2018[,1:8], ncp = 2, row.w = var_obj_2018$wt)

modif.rate(mca2018)$modif

mca2018 <- flip.mca(mca2018, dim = 1)

ggcloud_variables(mca2018, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3) + 
  labs(title = "MCA 2018")


#2020
var_obj_2020 <- latinobarometro_sel %>%
  filter(anio == 2020) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2020 <- speMCA(var_obj_2020[,1:8], ncp = 2, row.w = var_obj_2020$wt)

modif.rate(mca2020)$modif

mca2020 <- flip.mca(mca2020, dim = 1)

ggcloud_variables(mca2020, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3) + 
  labs(title = "MCA 2020")

#2023
var_obj_2023 <- latinobarometro_sel %>%
  filter(anio == 2023) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2023 <- speMCA(var_obj_2023[,1:8], ncp = 2, row.w = var_obj_2023$wt)

modif.rate(mca2023)$modif

mca2023 <- flip.mca(mca2023, dim = 1)

ggcloud_variables(mca2023, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3) + 
  labs(title = "MCA 2023")

#2024
var_obj_2024 <- latinobarometro_sel %>%
  filter(anio == 2024) %>%
  select(trabajo_f, nivel_ed, bienes_lava, bienes_celular, bienes_auto, bienes_cloaca,
         bienes_aguacal, bienes_casa, wt, id_fila)

mca2024 <- speMCA(var_obj_2024[,1:8], ncp = 2, row.w = var_obj_2024$wt)

modif.rate(mca2024)$modif

mca2024 <- flip.mca(mca2024, dim = 1)

ggcloud_variables(mca2024, vlab = T, shapes = T, shapesize = 1.5, force = 2,
                  textsize = 2.3) + 
  labs(title = "MCA 2024")



#Pego los puntajes factoriales
coords <- bind_rows(
  data.frame(anio = 2011, id_fila = var_obj_2011$id_fila, dim1 = mca2011$ind$coord[, 1]),
  data.frame(anio = 2013, id_fila = var_obj_2013$id_fila, dim1 = mca2013$ind$coord[, 1]),
  data.frame(anio = 2015, id_fila = var_obj_2015$id_fila, dim1 = mca2015$ind$coord[, 1]),
  data.frame(anio = 2017, id_fila = var_obj_2017$id_fila, dim1 = mca2017$ind$coord[, 1]),
  data.frame(anio = 2018, id_fila = var_obj_2018$id_fila, dim1 = mca2018$ind$coord[, 1]),
  data.frame(anio = 2020, id_fila = var_obj_2020$id_fila, dim1 = mca2020$ind$coord[, 1]),
  data.frame(anio = 2023, id_fila = var_obj_2023$id_fila, dim1 = mca2023$ind$coord[, 1]),
  data.frame(anio = 2024, id_fila = var_obj_2024$id_fila, dim1 = mca2024$ind$coord[, 1])
)

estandarizar_ponderado <- function(x, w) {
  media_ponderada <- sum(x * w) / sum(w)
  var_ponderada <- sum(w * (x - media_ponderada)^2) / sum(w)
  desv_ponderada <- sqrt(var_ponderada)
  return((x - media_ponderada) / desv_ponderada)
}

latinobarometro_sel <- latinobarometro_sel %>%
  left_join(coords, by = c("anio", "id_fila")) %>% 
  mutate(dim1_std = estandarizar_ponderado(dim1, wt),
         dim1_01= scales::rescale(dim1, to = c(0, 1)))


rm(coords, var_obj_2011, var_obj_2013, var_obj_2015, var_obj_2017, var_obj_2018, var_obj_2020, var_obj_2023, var_obj_2024,
   mca2011, mca2013, mca2015, mca2017, mca2018, mca2020, mca2023, mca2024)

```

## Modificación de variables

```{r Arreglo de variables}
#centrar y escalar variables
latinobarometro_sel <- latinobarometro_sel %>% 
  group_by(anio_pais) %>% 
  mutate(edad_cw = scale(edad, center = T, scale = T),
         estatus_obj = scale(dim1_std, center = T),
         estatus_01 = scales::rescale(dim1_std, to = c(0, 1)),
         ideologia_cw = scale(ideologia, center = T, scale = T)) %>% 
  ungroup() %>% 
  mutate(
    clase_media = factor(case_when(clase_subjetiva_f %in% c("Alta", "Media alta",
                                                            "Media") ~ 1,
                                   TRUE ~ 0)),
    clase_media2 = factor(case_when(clase_subjetiva_f %in% c("Alta", "Media alta") ~ 1,
                                   TRUE ~ 0)),
    clase_media3 = factor(case_when(clase_subjetiva_f %in% c("Media") ~ 1,
                                   TRUE ~ 0)),
    pib_ppa_cgm = scale(pib_ppa,center = T, scale = T),
    gini_cgm = scale(gini, center = T, scale = T),
    informalidad_cgm = scale(informalidad, center = T, scale = T),
    ocupaciones_medias_cgm = scale(ocupaciones_medias, center = T, scale = T),
    ocupaciones_profesionales_cgm = scale(ocupaciones_profesionales, center = T, scale = T),
    empleo_cgm = scale(emp_publico, center = T, scale = T),
    palma_cgm = scale(palma, center = T, scale = T),
    pib_log = log10(pib_ppa),
    cuentapropia_cgm = scale(cuentapropia, center = T, scale = T))

promedio_gen <- latinobarometro_sel %>% 
  summarise(promedio_gen = weighted.mean(estatus_01, wt = wt, na.rm = TRUE)) %>% 
  pull(promedio_gen)

latinobarometro_sel %>%
  group_by(iso3) %>%
  summarise(
  promedio = weighted.mean(estatus_01, wt = wt, na.rm = T)) %>%
  ggplot(aes(x = fct_reorder(iso3, promedio, .desc = T), y = promedio)) +
  geom_hline(yintercept = promedio_gen) +
  geom_segment(aes(x=iso3, xend=iso3, y=promedio_gen, yend=promedio), color="orange") +
  geom_point( color="orange", size=4) +
  geom_axis_flags(breaks = latinobarometro_sel$iso3,
                  labels = latinobarometro_sel$pais_f,
                  country_icons = latinobarometro_sel$iso3,
                  width = 20,
                  lineheight = 2) +
  # labs(title = "Gráfico 1. Índice de estratificación social objetiva",
  #      subtitle = "Países de América Latina. 2011-2024",
  #      caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_text(size = 10)) 

ggsave("graficos/clase_subjetiva/indice_estratificacion.png", width = 8, height = 5, dpi = 300)

```

# Análisis descriptivo

```{r gráficos descriptivos} 
latinobarometro_sel %>% 
  filter(!is.na(clase_subjetiva4)) %>% 
  group_by(anio, pais_f, clase_subjetiva4) %>% 
  tally(wt) %>% 
  mutate(porcentaje = n / sum(n)) %>% 
  ggplot(aes(x = as.character(anio), y = porcentaje, fill = clase_subjetiva4)) +
  geom_col(position = "fill") +
  # labs(
  #   title = "Gráfico 3. Distribución de la población según clase subjetiva",
  #   subtitle = "Países seleccionados de América Latina. 2011-2024",
  #   fill = "Clase subjetiva",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro"
  # ) +
  scale_fill_locuszoom() +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
    axis.text.y = element_text(size = 8), 
    legend.position = "bottom",
    strip.text = element_text(color = "black")
  ) +
  facet_wrap(~pais_f, ncol = 4)

ggsave("graficos/clase_subjetiva/dist_clase_sub.png", width = 8, height = 5, dpi = 300)


tabla <- latinobarometro_sel %>% 
  filter(!is.na(clase_subjetiva4)) %>% 
  group_by(anio, pais_f, clase_subjetiva4) %>% 
  tally(wt) %>% 
  mutate(porcentaje = round(n / sum(n)*100, digits = 2)) %>% 
  select(!n) %>% 
  pivot_wider(names_from = anio, values_from = porcentaje) %>% 
  flextable() %>% 
  autofit()

save_as_docx(tabla, path = "tablas/evolucion_clasesub.docx")

prom_clase_media <- latinobarometro_sel %>% 
  filter(!is.na(clase_media)) %>%
  group_by(anio, pais_f, clase_media) %>%
  tally(wt) %>% 
  mutate(porcentaje = n / sum(n)) %>% 
  filter(clase_media == 1) %>%
  ungroup() %>% 
  summarise(promedio = mean(porcentaje, na.rm = TRUE))

latinobarometro_sel %>% 
  filter(!is.na(clase_media)) %>% 
  group_by(anio, pais_f, clase_media) %>% 
  tally(wt) %>% 
  mutate(porcentaje = n / sum(n)) %>% 
  filter(clase_media == 1) %>% 
  ggplot(aes(x = as.character(anio), y = porcentaje)) +
  geom_col(fill = "steelblue") +
  geom_hline(yintercept = prom_clase_media$promedio, linetype = "dashed", color = "red") +
  # labs(
  #   title = "Porcentaje de personas que se consideran clase media, media alta y alta",
  #   subtitle = "Países seleccionados de América Latina. 2011-2024",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro"
  # ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(angle = 45, hjust = 1, size = 7),
    axis.text.y = element_text(size = 8),
    strip.text = element_text(color = "black")
  ) +
  facet_wrap(~pais_f, ncol = 4)

ggsave("graficos/clase_subjetiva/dist_clase_media.png", width = 8, height = 5, dpi = 300)



# Porcentaje de clase media por país y año
por_pais <- latinobarometro_sel %>%
  filter(!is.na(clase_media)) %>%
  group_by(anio, pais_f, clase_media) %>%
  tally(wt = wt) %>%
  mutate(porcentaje = n / sum(n)) %>%
  filter(clase_media == 1) %>%
  ungroup()

# Porcentaje de clase media total por año (todos los países)
datos_clasemedia <- latinobarometro_sel %>%
  filter(!is.na(clase_media)) %>%
  group_by(anio, clase_media) %>%
  tally(wt = wt) %>%
  mutate(porcentaje_clasemedia = n / sum(n)) %>%
  filter(clase_media == 1) %>%
  ungroup()

# Gráfico con puntos por país y línea de tendencia por año
ggplot() +
  # Puntos por país
  geom_point(data = por_pais,
             aes(x = as.character(anio), y = porcentaje, color = "Clase media por país y año"),
             alpha = 0.7) +
  # Línea de promedio general
  geom_line(data = datos_clasemedia,
            aes(x = as.character(anio), y = porcentaje_clasemedia, color = "Clase media promedio general", group = 1),
            size = .7) +
  facet_wrap(~pais_f, ncol = 4) +
  scale_color_locuszoom() +
  # labs(
  #   title = "Gráfico 2. Porcentaje de personas que se consideran clase media, media-alta y alta",
  #   subtitle = "Países seleccionados de América Latina. 2011-2024",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro"
  # ) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), breaks = seq(0, .7, .2), limits = c(0, .7)) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, size = 8),
    axis.text.y = element_text(size = 8),
    strip.text = element_text(color = "black"),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size = 9)
  )


ggsave("graficos/clase_subjetiva/dist_clase_media_puntos.png", width = 8, height = 5, dpi = 300)
  
  
  
  
```

```{r pirámides}
latinobarometro_sel %>% 
  filter(!is.na(clase_subjetiva4), anio == 2024) %>% 
  group_by(pais_f, clase_subjetiva4) %>% 
  tally(wt) %>% 
  mutate(porcentaje = n / sum(n) * 100,
         porcentaje_neg = -porcentaje) %>% 
  ggplot() +
  geom_bar(aes(x= fct_rev(clase_subjetiva4), y=porcentaje), stat="identity", fill = "skyblue", alpha = 0.8) +
  geom_bar(aes(x= fct_rev(clase_subjetiva4), y=porcentaje_neg), stat="identity", fill = "skyblue", alpha = 0.8) +
  coord_flip() +
  scale_y_continuous(labels = function(x) paste0(abs(x), "%")) +
  # labs(
  #   title = "Gráfico 5. Distribución de la población según clase subjetiva",
  #   subtitle = "Países seleccionados de América Latina. 2024",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro"
  # ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(size = 8),
    strip.text = element_text(color = "black")
  ) +
  facet_wrap(~pais_f, ncol = 4)

ggsave("graficos/clase_subjetiva/piramides_sub.png", width = 8, height = 5, dpi = 300)


latinobarometro_sel %>%
  filter(!is.na(clase_subjetiva4), anio == 2024) %>%
  ggplot(aes(x = 1, y = estatus_01, weight = wt)) +   # x = constante para un solo violín
  geom_violin(fill = "skyblue", alpha = 0.8) +
  # labs(
  #   title = "Gráfico 4. Distribución de la población según estatus objetivo (0-1)",
  #   subtitle = "Países seleccionados de América Latina. 2024",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro"
  # ) +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.y = element_text(size = 8),
    axis.text.x = element_blank(),
    strip.text = element_text(color = "black")
  ) +
  facet_wrap(~ pais_f)

ggsave("graficos/clase_subjetiva/piramides_obj.png", width = 8, height = 5, dpi = 300)

```

```{r Datos contextuales y clase subjetiva}
latinobarometro_sel2 <- latinobarometro_sel %>% 
  filter(anio < 2024)

# PBI
latinobarometro_sel2 %>% 
  filter(!is.na(clase_subjetiva4)) %>%
  group_by(anio_pais, pib_ppa, clase_media) %>% 
  tally(wt) %>% 
  mutate(porcentaje = n / sum(n)) %>% 
  filter(clase_media == 1) %>%
  ggplot(aes(x = pib_ppa, y = porcentaje)) +
  geom_point() +
  geom_smooth(
    method = "loess",
    se = T,
    color = "skyblue",
    linewidth = 1,
    aes(linetype = "Loess")
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 1.5) +
  # labs(
  #   title = "Gráfico 6. PIB per cápita y % de población identificada con la clase media",
  #   subtitle = "Países seleccionados de América Latina. 2011-2023. Curva LOESS ajustada",
  #   x = "PBI per cápita (dólar PPA)",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 8)) +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none"
  )

ggsave("graficos/clase_subjetiva/pib_clase_media.png", width = 8, height = 5, dpi = 300)

# Gini
latinobarometro_sel2 %>%
  filter(!is.na(clase_subjetiva4)) %>%
  group_by(anio_pais, gini, clase_media) %>% 
  tally(wt) %>% 
  mutate(porcentaje = n / sum(n)) %>% 
  filter(clase_media == 1) %>%
  ggplot(aes(x = gini, y = porcentaje)) +
  geom_point() +
  geom_smooth(
    method = "loess",
    se = T,
    color = "skyblue",
    linewidth = 1,
    aes(linetype = "Loess")
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 1.5) +
  # labs(
  #   title = "Gráfico 7. Índice de Gini y % de población identificada con la clase media",
  #   subtitle = "Países seleccionados de América Latina. 2011-2023. Curva LOESS ajustada",
  #   x = "Índice de Gini",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 8)) +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none"
  )

ggsave("graficos/clase_subjetiva/gini_clase_media.png", width = 8, height = 5, dpi = 300)

# Ocupaciones medias
latinobarometro_sel2 %>%
  filter(!is.na(clase_subjetiva4)) %>%
  group_by(anio_pais, ocupaciones_medias, clase_media) %>%
  tally(wt) %>%
  mutate(porcentaje = n / sum(n)) %>%
  filter(clase_media == 1) %>%
  ggplot(aes(x = ocupaciones_medias, y = porcentaje)) +
  geom_point() +
  geom_smooth(
    method = "loess",
    se = T,
    color = "skyblue",
    linewidth = 1,
    aes(linetype = "Loess")
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 1.5) +
  # labs(
  #   title = "Gráfico 8. % de ocupaciones medias y % de población identificada con la clase media",
  #   subtitle = "Países seleccionados de América Latina. 2011-2023. Curva LOESS ajustada",
  #   x = "% de ocupaciones medias",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 8),
                     labels = function(x) paste0(x, "%")) +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none"
  )
  

ggsave("graficos/clase_subjetiva/ocupaciones_clase_media.png", width = 8, height = 5, dpi = 300)

# Informalidad
latinobarometro_sel2 %>%
  filter(!is.na(clase_subjetiva4)) %>%
  group_by(anio_pais, informalidad, clase_media) %>%
  tally(wt) %>%
  mutate(porcentaje = n / sum(n)) %>%
  filter(clase_media == 1) %>%
  ggplot(aes(x = informalidad, y = porcentaje)) +
  geom_point() +
  geom_smooth(
    method = "loess",
    se = T,
    color = "skyblue",
    linewidth = 1,
    aes(linetype = "Loess")
  ) +
  ggrepel::geom_text_repel(aes(label = anio_pais), size = 1.5) +
  # labs(
  #   title = "Gráfico 9. Tasa de informalidad y % de población identificada con la clase media",
  #   subtitle = "Países seleccionados de América Latina. 2011-2023. Curva LOESS ajustada",
  #   x = "Tasa de informalidad",
  #   caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 8),
                     labels = function(x) paste0(x, "%")) +
  theme(
    axis.title.y = element_blank(),
    legend.position = "none"
  )

ggsave("graficos/clase_subjetiva/informalidad_clase_media.png", width = 8, height = 5, dpi = 300)

```



# Modelos multinivel

```{r Modelos multinivel}
latinobarometro_sel2 <- latinobarometro_sel2 %>% 
  mutate(anio = as.factor(anio),
         just_dist_ingresos_f = relevel(just_dist_ingresos_f, ref = "Muy injusta"),
         situacion_eco_pais_f = relevel(situacion_eco_pais_f, ref = "Muy mala"),
         categoria = case_when(estado_ocupacional_f %in% c("Temporalmente no trabaja",
                                                           "Retirado/pensionado",
                                                           "No trabaja",
                                                           "Estudiante") ~ "No trabaja",
                               TRUE ~ estado_ocupacional_f))

#Modelo nulo--------
mod1 <- glmer(clase_media ~ 1 + (1 | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"), weights = wt)

#ICC general
print(icc(mod1))

# Extraer varianzas
vc <- as.data.frame(VarCorr(mod1))
var_pais <- vc[vc$grp == "pais_f", "vcov"]
var_anio_pais <- vc[vc$grp == "anio:pais_f", "vcov"]

# Varianza residual logística
var_resid <- (pi^2) / 3

# ICC por nivel
icc_pais <- var_pais / (var_pais + var_anio_pais + var_resid)
icc_anio_pais <- var_anio_pais / (var_pais + var_anio_pais + var_resid)

data.frame(
  Nivel = c("País", "Año dentro de país"),
  ICC = c(icc_pais, icc_anio_pais)
)

#Modelo 2------
mod2 <- glmer(clase_media ~ edad_cw + sexo2 + estatus_obj + ideologia_cw +
                situacion_eco_pais_f + just_dist_ingresos_f + (1 | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"),
              weights = wt)  

#Modelo 3---------
mod3 <- glmer(clase_media ~ edad_cw + estatus_obj + sexo2 + ideologia_cw +
                situacion_eco_pais_f + just_dist_ingresos_f + pib_ppa_cgm + ocupaciones_medias_cgm + informalidad_cgm + gini_cgm + (1 | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"), weights = wt)

#Modelo 4a con interacciones----------
mod4a <- glmer(clase_media ~  estatus_obj * pib_ppa_cgm + edad_cw + sexo2 + ideologia_cw  +
                 situacion_eco_pais_f + just_dist_ingresos_f + 
                 ocupaciones_medias_cgm + informalidad_cgm + gini_cgm + (1 | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"), weights = wt)

# Modelo 4b con interacciones---------
mod4b <- glmer(clase_media ~  estatus_obj * informalidad_cgm + edad_cw + sexo2 + ideologia_cw  + situacion_eco_pais_f + just_dist_ingresos_f + 
                 pib_ppa_cgm + ocupaciones_medias_cgm + gini_cgm + (1 | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"), weights = wt)


# Modelo 4c con interacciones---------
mod4c <- glmer(clase_media ~  estatus_obj * ocupaciones_medias_cgm + edad_cw + sexo2 + ideologia_cw  + situacion_eco_pais_f + just_dist_ingresos_f + 
                 pib_ppa_cgm + informalidad_cgm + gini_cgm + (1 | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"), weights = wt)

# Modelo 4d con interacciones---------
mod4d <- glmer(clase_media ~  estatus_obj * gini_cgm + edad_cw + sexo2 + ideologia_cw  + situacion_eco_pais_f + just_dist_ingresos_f + 
                 pib_ppa_cgm + ocupaciones_medias_cgm + informalidad_cgm + (1 | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"), weights = wt)

# Modelo 5 con pendiente aleatoria---------
mod5 <- glmer(clase_media ~  estatus_obj + edad_cw + sexo2 + ideologia_cw  + 
                situacion_eco_pais_f + just_dist_ingresos_f + pib_ppa_cgm + informalidad_cgm + gini_cgm + ocupaciones_medias_cgm + (1 + estatus_obj | pais_f/anio), data = latinobarometro_sel2, family = binomial(link = "logit"), weights = wt)


VarCorr(mod5)


tab_model(mod3, mod4a, mod4b, mod4c, mod4d, mod5, 
          p.style = "stars",
          show.ci = F,
          show.icc = T,
          show.aic = T,
          transform = NULL,
          p.threshold = c(0.1, 0.05, 0.01))


# plot_model(mod3, 
#            type = "est", 
#            transform = "exp",  # para mostrar Odds Ratios
#            show.values = TRUE, 
#            value.offset = 0.3,
#            title = "Efectos fijos sobre la probabilidad de autopercibirse clase media",
#            vline.color = "grey") +
#   theme_minimal()

```




```{r Interceptos aleatorios}

re <- ranef(mod5)$`anio:pais_f` %>% 
  as.data.frame() %>%
  rename(effect = `(Intercept)`) %>%
  mutate(anio_pais = rownames(ranef(mod5)$`anio:pais_f`)) %>% 
  arrange(desc(effect)) %>%
  slice(c(1:10, (n() - 9):n()))

ggplot(re, aes(x = reorder(anio_pais, effect), y = effect)) +
  geom_point(color = "steelblue", size = 3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  coord_flip() +
  labs(y = "Intercepto aleatorios", 
       title = "Interceptos aleatorios más fuertes por año y país",
       subtitle = "Países seleccionados de América Latina. 2011-2023",
       caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  theme(axis.text.y = element_text(size = 7),
        axis.title.y = element_blank()) 

ggsave("graficos/clase_subjetiva/interceptos_aleatorios_anio_pais.png", width = 8, height = 5, dpi = 300)


re <- ranef(mod5)$pais_f %>% 
  as.data.frame() %>%
  rename(effect = `(Intercept)`) %>%
  mutate(pais = rownames(ranef(mod5)$pais_f)) %>% 
  arrange(desc(effect)) %>%
  slice(c(1:10, (n() - 9):n()))

ggplot(re, aes(x = reorder(pais, effect), y = effect)) +
  geom_point(color = "steelblue", size = 3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  coord_flip() +
  labs(y = "Intercepto aleatorios", 
       title = "Interceptos aleatorios por país",
       subtitle = "Países seleccionados de América Latina. 2011-2023",
       caption = "Fuente: elaboración propia en base a Latinobarómetro") +
  theme(axis.text.y = element_text(size = 8),
        axis.title.y = element_blank()) 

ggsave("graficos/clase_subjetiva/interceptos_aleatorios_pais.png", width = 8, height = 5, dpi = 300)


```


```{r Pendiente aleatoria}

# Asegurar que el nombre del país quede como columna
ranef_slope <- ranef(mod5)$pais_f %>%
  as.data.frame() %>%
  rownames_to_column("pais") %>%
  rename(pendiente_estatus = estatus_obj) %>%
  arrange(desc(pendiente_estatus))

# Gráfico de las pendientes aleatorias
ggplot(ranef_slope, aes(x = reorder(pais, pendiente_estatus), y = pendiente_estatus)) +
  geom_point(color = "steelblue", size = 3) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  coord_flip() +
  labs(
    y = "Pendiente aleatoria",
    title = "Pendientes aleatorias de estatus objetivo por país",
    subtitle = "Países seleccionados de América Latina. 2011-2023",
    caption = "Fuente: elaboración propia en base a Latinobarómetro"
  ) +
  theme(
    axis.text.y = element_text(size = 8),
    axis.title.y = element_blank()
  )

ggsave("graficos/clase_subjetiva/pendientes_aleatorias_pais.png", width = 8, height = 5, dpi = 300)


```

```{r interceptos y pendientes aleatorias}
ranef_sel <- ranef(mod5)$`anio:pais_f` %>%
  as.data.frame() %>%
  rownames_to_column("anio_pais") %>%
  rename(pendiente_estatus = estatus_obj, intercepto = `(Intercept)`) %>%
  separate(anio_pais, into = c("anio", "pais_f"), sep = ":") %>%
  mutate(anio = as.numeric(anio)) %>% 
  filter(anio %in% c(2011, 2017, 2023))

efectos_fijos <- fixef(mod5)
intercepto_fijo <- efectos_fijos["(Intercept)"]
pendiente_fija <- efectos_fijos["estatus_obj"]

ranef_sel <- ranef_sel %>%
  mutate(
    intercepto_total = intercepto + intercepto_fijo,
    pendiente_total = exp(pendiente_estatus + pendiente_fija)
  )

ggplot(ranef_sel, aes(x = plogis(intercepto_total), y = pendiente_total)) +
  geom_point(size = 2.7, alpha = 0.7) +
  geom_hline(yintercept = exp(pendiente_fija), linetype = "dashed", color = "skyblue") +
  geom_vline(xintercept = plogis(intercepto_fijo), linetype = "dashed", color = "skyblue") +
  ggrepel::geom_text_repel(aes(label = pais_f), size = 2.5) +
  labs(
    x = "Probabilidad promedio de posicionarse en la clase media",
    y = "Pendiente del estatus social objetivo (odds ratio)",
    # title = "Gráfico 10. Interacción entre pendientes e interceptos aleatorios (modelo 5)",
    # subtitle = "Países seleccionados de América Latina. Años 2011, 2017 y 2023",
    # caption = "Fuente: elaboración propia en base a Latinobarómetro"
  ) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  theme(
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    strip.text = element_text(color = "black"),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10)) +
  facet_wrap(~ factor(anio))

ggsave("graficos/clase_subjetiva/interceptos_pendientes_aleatorias.png", width = 8, height = 5, dpi = 300)

#Ver que sucede en momentos de crisis

ranef_sel <- ranef(mod5)$`anio:pais_f` %>%
  as.data.frame() %>%
  rownames_to_column("anio_pais") %>%
  rename(pendiente_estatus = estatus_obj, intercepto = `(Intercept)`) %>%
  separate(anio_pais, into = c("anio", "pais_f"), sep = ":") %>%
  mutate(anio = as.numeric(anio))

efectos_fijos <- fixef(mod5)
intercepto_fijo <- efectos_fijos["(Intercept)"]
pendiente_fija <- efectos_fijos["estatus_obj"]

ranef_sel <- ranef_sel %>%
  mutate(
    intercepto_total = intercepto + intercepto_fijo,
    pendiente_total = exp(pendiente_estatus + pendiente_fija)
  )

ggplot(ranef_sel, aes(x = plogis(intercepto_total), y = pendiente_total)) +
  geom_point(size = 2, alpha = 0.7) +
  geom_hline(yintercept = exp(pendiente_fija), linetype = "dashed", color = "skyblue") +
  geom_vline(xintercept = plogis(intercepto_fijo), linetype = "dashed", color = "skyblue") +
  ggrepel::geom_text_repel(aes(label = pais_f), size = 2.5) +
  labs(
    x = "Probabilidad promedio de posicionarse en la clase media",
    y = "Pendiente del estatus social objetivo (odds ratio)",
    title = "Gráfico 10. Interacción entre pendientes e interceptos aleatorios (modelo 5)",
    subtitle = "Países seleccionados de América Latina. Años 2011, 2017 y 2023",
    caption = "Fuente: elaboración propia en base a Latinobarómetro"
  ) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 8)) +
  theme(
    axis.text.x = element_text(size = 8),
    axis.text.y = element_text(size = 8),
    strip.text = element_text(color = "black"),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10)) +
  facet_wrap(~ factor(anio))

ggsave("graficos/clase_subjetiva/interceptos_pendientes_aleatorias_total.png", width = 8, height = 5, dpi = 300)

```


