# Carga de base ----------------------------
rm(list = ls())

pacman::p_load(tidyverse)

load("bases/latinobarometro.RData")

#Construcción de variables---------
latinobarometro <- latinobarometro %>% 
  mutate(anio = case_when(numinves == 16 ~ 2011,
                          numinves == 17 ~ 2013,
                          numinves == 18 ~ 2015,
                          numinves == 23 ~ 2023,
                          NUMINVES == 2018 ~ 2018,
                          TRUE ~ numinves),
         pais = ifelse(is.na(idenpa), IDENPA, idenpa),
         pais_f = factor(latinobarometro$idenpa, labels = 
                           c("Arg", "Bol", "Bra", "Chi", "Col", "Cri", "Dom", "Ecu", 
                             "Slv", "Gua", "Hon", "Mex", "Nic", "Pan", "Par", "Per",
                             "Esp", "Uru", "Ven")),
         entrevista = ifelse(anio == 2018, NUMENTRE, numentre),
         wt = case_when(anio == 1998 ~ pondera,
                        anio == 2018 ~ WT,
                        TRUE ~ wt),
         sexo2 = case_when(anio == 1998 ~ s1,
                           anio == 2000 ~ S1,
                           anio == 2001 ~ s1,
                           anio == 2002 ~ s1,
                           anio == 2003 ~ s1,
                           anio == 2004 ~ s1,
                           anio == 2005 ~ s6,
                           anio == 2006 ~ s6,
                           anio == 2007 ~ s10,
                           anio == 2008 ~ s8,
                           anio == 2009 ~ s5,
                           anio == 2010 ~ S7,
                           anio == 2011 ~ S16,
                           anio == 2013 ~ S10,
                           anio == 2015 ~ S12,
                           anio == 2016 ~ sexo,
                           anio == 2017 ~ sexo,
                           anio == 2018 ~ SEXO,
                           anio == 2020 ~ sexo,
                           anio == 2023 ~ sexo,
                           TRUE ~ NA_real_),
         edad = case_when(anio == 1998 ~ s2,
                          anio == 2000 ~ S2,
                          anio == 2001 ~ s2,
                          anio == 2002 ~ s2,
                          anio == 2003 ~ s2,
                          anio == 2004 ~ s2,
                          anio == 2005 ~ s7,
                          anio == 2006 ~ s7,
                          anio == 2007 ~ s11,
                          anio == 2008 ~ s9,
                          anio == 2009 ~ s6,
                          anio == 2010 ~ S8,
                          anio == 2011 ~ S17,
                          anio == 2013 ~ S11,
                          anio == 2015 ~ S13,
                          anio == 2016 ~ edad,
                          anio == 2017 ~ edad,
                          anio == 2018 ~ EDAD,
                          anio == 2020 ~ edad,
                          anio == 2023 ~ edad,
                          TRUE ~ NA_real_),
         años_ed = case_when(anio == 1998 ~ s11,
                             anio == 2000 ~ S6,
                             anio == 2001 ~ s6,
                             anio == 2002 ~ s6,
                             anio == 2003 ~ s6,
                             anio == 2004 ~ s6,
                             anio == 2005 ~ s11,
                             anio == 2006 ~ s11,
                             anio == 2007 ~ s15,
                             anio == 2008 ~ s15,
                             anio == 2009 ~ s12,
                             anio == 2010 ~ S14,
                             anio == 2011 ~ S21,
                             anio == 2013 ~ S17,
                             anio == 2015 ~ S19,
                             anio == 2016 ~ S13,
                             anio == 2017 ~ S14,
                             anio == 2018 ~ S10,
                             anio == 2020 ~ s16,
                             anio == 2023 ~ S11,
                             TRUE ~ NA_real_),
         estado_ocupacional = case_when(anio == 1998 ~ s7a,
                                        anio == 2000 ~ S8A,
                                        anio == 2001 ~ s8a,
                                        anio == 2002 ~ s8a,
                                        anio == 2003 ~ s8a,
                                        anio == 2004 ~ s8a,
                                        anio == 2005 ~ s13a,
                                        anio == 2006 ~ s13a,
                                        anio == 2007 ~ s17a,
                                        anio == 2008 ~ s17a,
                                        anio == 2009 ~ s14a,
                                        anio == 2010 ~ S16A,
                                        anio == 2011 ~ S23A,
                                        anio == 2013 ~ S19_A,
                                        anio == 2015 ~ S21_A,
                                        anio == 2016 ~ S18A,
                                        anio == 2017 ~ S18_A,
                                        anio == 2018 ~ S14A,
                                        anio == 2020 ~ s24_a,
                                        anio == 2023 ~ S18_A,
                                        TRUE ~ NA_real_),
         trabajo_anterior = case_when(anio == 1998 ~ s7b,
                                      anio == 2000 ~ S8B,
                                      anio == 2001 ~ s8b,
                                      anio == 2002 ~ s8b,
                                      anio == 2003 ~ s8b,
                                      anio == 2004 ~ s8b,
                                      anio == 2005 ~ s13b,
                                      anio == 2006 ~ s13b,
                                      anio == 2007 ~ s17b,
                                      anio == 2008 ~ s17b,
                                      anio == 2009 ~ s14b,
                                      anio == 2010 ~ S16B,
                                      anio == 2011 ~ S23B,
                                      anio == 2013 ~ S19_B,
                                      anio == 2015 ~ S21_B,
                                      anio == 2016 ~ S18B,
                                      anio == 2017 ~ S18_B,
                                      anio == 2018 ~ S14B,
                                      anio == 2020 ~ s24_b,
                                      anio == 2023 ~ S18_B,
                                      TRUE ~ NA_real_),
         trabajo_actual = case_when(anio == 1998 ~ s8,
                                    anio == 2000 ~ S9,
                                    anio == 2001 ~ s9,
                                    anio == 2002 ~ s9,
                                    anio == 2003 ~ s9,
                                    anio == 2004 ~ s9,
                                    anio == 2005 ~ s14,
                                    anio == 2006 ~ s14,
                                    anio == 2007 ~ s18,
                                    anio == 2008 ~ s18,
                                    anio == 2009 ~ s15,
                                    anio == 2010 ~ S17,
                                    anio == 2011 ~ S24,
                                    anio == 2013 ~ S20,
                                    anio == 2015 ~ S22,
                                    anio == 2016 ~ S19,
                                    anio == 2017 ~ S19,
                                    anio == 2018 ~ S15,
                                    anio == 2020 ~ s25,
                                    anio == 2023 ~ S19,
                                    TRUE ~ NA_real_),
         clase_subjetiva = case_when(anio == 2011 ~ S14,
                                     anio == 2013 ~ S8,
                                     anio == 2015 ~ S6,
                                     anio == 2017 ~ S1,
                                     anio == 2018 ~ S1,
                                     anio == 2020 ~ s1,
                                     anio == 2023 ~ S2,
                                     TRUE ~ NA_real_)
  )



latinobarometro <- latinobarometro %>% 
  mutate(democracia = case_when(anio == 1998 ~ sp28,
                                anio == 2000 ~ P29ST,
                                anio == 2001 ~ p46st,
                                anio == 2002 ~ p32st,
                                anio == 2003 ~ p14st,
                                anio == 2004 ~ p13st,
                                anio == 2005 ~ p16st,
                                anio == 2006 ~ p17st,
                                anio == 2007 ~ p9st,
                                anio == 2008 ~ p13st,
                                anio == 2009 ~ p10st,
                                anio == 2010 ~ P10ST,
                                anio == 2011 ~ P13ST,
                                anio == 2013 ~ P12STGBS,
                                anio == 2015 ~ P11STGBS,
                                anio == 2016 ~ P8STGBS,
                                anio == 2017 ~ P8STGBS,
                                anio == 2018 ~ P12STGBS,
                                anio == 2020 ~ p10stgbs,
                                anio == 2023 ~ P10STGBS),
         satisf_democracia = case_when(anio == 1998 ~ sp29,
                                       anio == 2000 ~ P30ST,
                                       anio == 2001 ~ p45st,
                                       anio == 2002 ~ p33st,
                                       anio == 2003 ~ p15st,
                                       anio == 2004 ~ p14st,
                                       anio == 2005 ~ p18st,
                                       anio == 2006 ~ p21st,
                                       anio == 2007 ~ p12st,
                                       anio == 2008 ~ p22st_a,
                                       anio == 2009 ~ p12st_a,
                                       anio == 2010 ~ P11ST_A,
                                       anio == 2011 ~ P14ST_A,
                                       anio == 2013 ~ P13TGB_A,
                                       anio == 2015 ~ P12TG_A,
                                       anio == 2016 ~ P9STGBSA,
                                       anio == 2017 ~ P9STGBSC_A,
                                       anio == 2018 ~ P13STGBS.A,
                                       anio == 2020 ~ P11STGBS_A,
                                       anio == 2023 ~ P11STGBS_A),
         garantia_politica = case_when(anio == 2007 ~ p18na,
                                       anio == 2008 ~ p26st_a,
                                       anio == 2009 ~ p15st_a,
                                       anio == 2011 ~ P41ST_A,
                                       anio == 2015 ~ P50ST_A,
                                       anio == 2020 ~ p47st_a,
                                       anio == 2023 ~ P41ST_A,
                                       TRUE ~ NA_real_),
         garantia_profesion = case_when(anio == 2007 ~ p18nb,
                                        anio == 2008 ~ p26st_b,
                                        anio == 2009 ~ p15st_b,
                                        anio == 2011 ~ P41ST_B,
                                        anio == 2015 ~ P50ST_B,
                                        anio == 2020 ~ p47st_b,
                                        anio == 2023 ~ P41ST_B,
                                        TRUE ~ NA_real_),
         garantia_medioambiente = case_when(anio == 2007 ~ p18nc,
                                            anio == 2008 ~ p26st_c,
                                            anio == 2009 ~ p15st_c,
                                            anio == 2011 ~ P41ST_C,
                                            anio == 2015 ~ P50ST_C,
                                            anio == 2020 ~ p47st_c,
                                            anio == 2023 ~ P41ST_C,
                                            TRUE ~ NA_real_),
         garantia_propprivada = case_when(anio == 2007 ~ p18nd,
                                          anio == 2008 ~ p26st_d,
                                          anio == 2009 ~ p15st_d,
                                          anio == 2011 ~ P41ST_D,
                                          anio == 2015 ~ P50ST_D,
                                          anio == 2020 ~ p47st_d,
                                          anio == 2023 ~ P41ST_D,
                                          TRUE ~ NA_real_),
         garantia_distriqueza = case_when(anio == 2007 ~ p18ne,
                                          anio == 2008 ~ p26st_e,
                                          anio == 2009 ~ p15st_e,
                                          anio == 2011 ~ P41ST_E,
                                          anio == 2015 ~ P50ST_E,
                                          anio == 2020 ~ p47st_e,
                                          anio == 2023 ~ P41ST_E,
                                          TRUE ~ NA_real_),
         garantia_genero = case_when(anio == 2007 ~ p18nf,
                                     anio == 2008 ~ p26st_f,
                                     anio == 2009 ~ p15st_f,
                                     anio == 2011 ~ P41ST_F,
                                     anio == 2015 ~ P50ST_F,
                                     anio == 2020 ~ p47st_f,
                                     anio == 2023 ~ P41ST_F,
                                     TRUE ~ NA_real_),
         garantia_oportunidades = case_when(anio == 2007 ~ p18ng,
                                            anio == 2008 ~ p26st_g,
                                            anio == 2009 ~ p15st_g,
                                            anio == 2011 ~ P41ST_G,
                                            anio == 2015 ~ P50ST_G,
                                            anio == 2020 ~ p47st_g,
                                            anio == 2023 ~ P41ST_G,
                                            TRUE ~ NA_real_),
         garantia_expresion = case_when(anio == 2007 ~ p18nh,
                                        anio == 2008 ~ p26st_h,
                                        anio == 2009 ~ p15st_h,
                                        anio == 2011 ~ P41ST_H,
                                        anio == 2015 ~ P50ST_H,
                                        anio == 2020 ~ p47st_h,
                                        anio == 2023 ~ P41ST_H,
                                        TRUE ~ NA_real_),
         garantia_religion = case_when(anio == 2007 ~ p18ni,
                                       anio == 2008 ~ p26st_i,
                                       anio == 2009 ~ p15st_i,
                                       anio == 2011 ~ P41ST_I,
                                       anio == 2015 ~ P50ST_I,
                                       anio == 2020 ~ p47st_i,
                                       anio == 2023 ~ P41ST_I,
                                       TRUE ~ NA_real_),
         garantia_crimen = case_when(anio == 2007 ~ p18nj,
                                     anio == 2008 ~ p26st_j,
                                     anio == 2009 ~ p15st_j,
                                     anio == 2011 ~ P41ST_J,
                                     anio == 2015 ~ P50ST_J,
                                     anio == 2020 ~ p47st_j,
                                     anio == 2023 ~ P41ST_J,
                                     TRUE ~ NA_real_),
         garantia_seguridadsocial = case_when(anio == 2007 ~ p18nk,
                                              anio == 2008 ~ p26st_k,
                                              anio == 2009 ~ p15st_k,
                                              anio == 2011 ~ P41ST_K,
                                              anio == 2015 ~ P50ST_K,
                                              anio == 2020 ~ p47st_k,
                                              anio == 2023 ~ P41ST_K,
                                              TRUE ~ NA_real_),
         garantia_solidaridad = case_when(anio == 2007 ~ p18nl,
                                         anio == 2008 ~ p26st_l,
                                         anio == 2009 ~ p15st_l,
                                         anio == 2011 ~ P41ST_L,
                                         anio == 2015 ~ P50ST_L,
                                         anio == 2020 ~ p47st_l,
                                         anio == 2023 ~ P41ST_L,
                                         TRUE ~ NA_real_),
         garantia_trabajo = case_when(anio == 2007 ~ p18nm,
                                      anio == 2008 ~ p26st_m,
                                      anio == 2009 ~ p15st_m,
                                      anio == 2011 ~ P41ST_M,
                                      anio == 2015 ~ P50ST_M,
                                      anio == 2020 ~ p47st_m,
                                      anio == 2023 ~ P41ST_M,
                                      TRUE ~ NA_real_),
         ideologia = case_when(anio == 1998 ~ sp52,
                               anio == 2000 ~ P52ST,
                               anio == 2001 ~ p54st,
                               anio == 2002 ~ p64st,
                               anio == 2003 ~ p60st,
                               anio == 2004 ~ p87st,
                               anio == 2005 ~ p34st,
                               anio == 2006 ~ p47st,
                               anio == 2007 ~ p67st,
                               anio == 2008 ~ p56st,
                               anio == 2009 ~ p69st,
                               anio == 2010 ~ P60ST,
                               anio == 2011 ~ P76ST,
                               anio == 2013 ~ P41ST,
                               anio == 2015 ~ P27ST,
                               anio == 2016 ~ P17ST,
                               anio == 2017 ~ P19STC,
                               anio == 2018 ~ P22ST,
                               anio == 2020 ~ p18st,
                               anio == 2023 ~ P16ST,
                               TRUE ~ NA_real_),
         pais_poderosos = case_when(anio == 2004 ~ p24wvs,
                                    anio == 2005 ~ p22st,
                                    anio == 2006 ~ p20stm,
                                    anio == 2007 ~ p16st,
                                    anio == 2008 ~ p25st,
                                    anio == 2009 ~ p22st,
                                    anio == 2010 ~ P17ST,
                                    anio == 2011 ~ P19ST,
                                    anio == 2013 ~ P14ST,
                                    anio == 2015 ~ P14ST,
                                    anio == 2016 ~ P10ST,
                                    anio == 2017 ~ P10ST,
                                    anio == 2018 ~ P14ST,
                                    anio == 2020 ~ P12ST,
                                    anio == 2023 ~ P12ST,
                                    TRUE ~ NA_real_),
         escala_pobriq_padres = case_when(anio == 2000 ~ P14CG_B,
                                          anio == 2004 ~ p9stb,
                                          anio == 2005 ~ p95st,
                                          anio == 2006 ~ p13st_b,
                                          anio == 2007 ~ p6stmb,
                                          anio == 2008 ~ p12st_b,
                                          anio == 2009 ~ p17st_b,
                                          anio == 2010 ~ P13ST_B,
                                          anio == 2011 ~ P11ST_B,
                                          anio == 2013 ~ P11ST_B,
                                          anio == 2018 ~ P10STC.B,
                                          anio == 2020 ~ p8st_b,
                                          TRUE ~ NA_real_),
         escala_pobriq_personal = case_when(anio == 2000 ~ P14CG_A,
                                            anio == 2004 ~ p9sta,
                                            anio == 2006 ~ p13st_a,
                                            anio == 2007 ~ p6stma,
                                            anio == 2008 ~ p12st_a,
                                            anio == 2009 ~ p17st_a,
                                            anio == 2010 ~ P13ST_A,
                                            anio == 2011 ~ P11ST_A,
                                            anio == 2013 ~ P11ST_A,
                                            anio == 2018 ~ P10STC.A,
                                            anio == 2020 ~ p8st_a,
                                            TRUE ~ NA_real_),
         escala_pobriq_hijos = case_when(anio == 2000 ~ P14CG_C,
                                         anio == 2004 ~ p9stc,
                                         anio == 2006 ~ p13st_c,
                                         anio == 2007 ~ p6stmc,
                                         anio == 2008 ~ p12st_c,
                                         anio == 2009 ~ p17st_c,
                                         anio == 2010 ~ P13ST_C,
                                         anio == 2011 ~ P11ST_C,
                                         anio == 2013 ~ P11ST_C,
                                         anio == 2018 ~ P10STC.C,
                                         anio == 2020 ~ p8st_c,
                                         TRUE ~ NA_real_),
         situacion_padres = case_when(anio == 1998 ~ sp9a,
                                      anio == 2000 ~ P13ST_A,
                                      anio == 2001 ~ p10sta,
                                      anio == 2002 ~ p3sta,
                                      anio == 2003 ~ p7sta,
                                      anio == 2004 ~ p8sta,
                                      anio == 2005 ~ p12sta,
                                      anio == 2007 ~ p5sta,
                                      TRUE ~ NA_real_),
         situacion_hijos = case_when(anio == 1998 ~ sp9b,
                                     anio == 2000 ~ P13ST_B,
                                     anio == 2001 ~ p10stb,
                                     anio == 2002 ~ p3stb,
                                     anio == 2003 ~ p7stb,
                                     anio == 2004 ~ p8stb,
                                     anio == 2005 ~ p12stb,
                                     anio == 2007 ~ p5stb,
                                     TRUE ~ NA_real_),
         just_dist_ingresos = case_when(anio == 2001 ~ p11st,
                                        anio == 2002 ~ p16st,
                                        anio == 2007 ~ p17st,
                                        anio == 2009 ~ p14st,
                                        anio == 2010 ~ P12ST,
                                        anio == 2011 ~ P12ST,
                                        anio == 2013 ~ P27ST,
                                        anio == 2015 ~ P18ST,
                                        anio == 2016 ~ P21ST,
                                        anio == 2017 ~ P20ST,
                                        anio == 2018 ~ P23ST,
                                        anio == 2020 ~ p19st_a,
                                        anio == 2023 ~ P17ST,
                                        TRUE ~ NA_real_),
         situacion_eco_pais = case_when(anio == 1998 ~ sp1,
                                        anio == 2000 ~ P1ST,
                                        anio == 2001 ~ p1st,
                                        anio == 2002 ~ p2sta,
                                        anio == 2003 ~ p1st,
                                        anio == 2004 ~ p2st,
                                        anio == 2005 ~ p2st,
                                        anio == 2006 ~ p2st,
                                        anio == 2007 ~ p100st,
                                        anio == 2008 ~ p4st,
                                        anio == 2009 ~ p3st_a,
                                        anio == 2010 ~ P3ST_A,
                                        anio == 2011 ~ P3ST_A,
                                        anio == 2013 ~ P3STGBS,
                                        anio == 2015 ~ P3STGBS,
                                        anio == 2016 ~ P4STGBS,
                                        anio == 2017 ~ P4STGBSC,
                                        anio == 2018 ~ P6STGBSC,
                                        anio == 2020 ~ p4stgbs,
                                        anio == 2023 ~ P5STGBS,
                                        TRUE ~ NA_real_),
         ing_subjetivo = case_when(anio == 1998 ~ sp83,
                                   anio == 2000 ~ P78ST,
                                   anio == 2001 ~ p88st,
                                   anio == 2002 ~ p67st,
                                   anio == 2003 ~ p90st,
                                   anio == 2004 ~ p89st,
                                   anio == 2005 ~ s1,
                                   anio == 2006 ~ s1,
                                   anio == 2007 ~ s2,
                                   anio == 2008 ~ s2,
                                   anio == 2009 ~ s2,
                                   anio == 2010 ~ S4,
                                   anio == 2011 ~ S10ICC12,
                                   anio == 2013 ~ S6,
                                   anio == 2015 ~ S4,
                                   anio == 2016 ~ S4,
                                   anio == 2017 ~ S5,
                                   anio == 2018 ~ S4,
                                   anio == 2020 ~ s4,
                                   anio == 2023 ~ S5,
                                   TRUE ~ NA_real_),
         pro_mercado = case_when(anio == 2003 ~ p22n_f,
                                 anio == 2004 ~ p22std,
                                 anio == 2005 ~ p25sta,
                                 anio == 2007 ~ p54stb,
                                 anio == 2008 ~ p57st_e,
                                 anio == 2009 ~ p81st_c,
                                 anio == 2010 ~ P75ST_B,
                                 anio == 2011 ~ P69ST_B,
                                 anio == 2013 ~ P60ST_A,
                                 anio == 2016 ~ P44STME,
                                 anio == 2017 ~ P27ST,
                                 anio == 2018 ~ P26ST,
                                 anio == 2020 ~ p62st_d,
                                 anio == 2023 ~ P54ST_B,
                                 TRUE ~ NA_real_),
         bienes_comp = case_when(anio == 1998 ~ s9d,
                                 anio == 2000 ~ S10D,
                                 anio == 2001 ~ s10d,
                                 anio == 2002 ~ s10d,
                                 anio == 2003 ~ s10d,
                                 anio == 2004 ~ s10d,
                                 anio == 2005 ~ s15d,
                                 anio == 2006 ~ s15d,
                                 anio == 2007 ~ s19d,
                                 anio == 2008 ~ s19d,
                                 anio == 2009 ~ s19f,
                                 anio == 2010 ~ S21F,
                                 anio == 2011 ~ S28D,
                                 anio == 2013 ~ S22_D,
                                 anio == 2015 ~ S24_C,
                                 anio == 2016 ~ S16C,
                                 anio == 2017 ~ S17_C,
                                 anio == 2018 ~ S21.C,
                                 anio == 2020 ~ s26_c,
                                 TRUE ~ NA_real_),
         bienes_lava = case_when(anio == 1998 ~ s9e,
                                 anio == 2000 ~ S10E,
                                 anio == 2001 ~ s10e,
                                 anio == 2002 ~ s10e,
                                 anio == 2003 ~ s10e,
                                 anio == 2004 ~ s10e,
                                 anio == 2005 ~ s15e,
                                 anio == 2006 ~ s15e,
                                 anio == 2007 ~ s19e,
                                 anio == 2008 ~ s19e,
                                 anio == 2009 ~ s19g,
                                 anio == 2010 ~ S21G,
                                 anio == 2011 ~ S28E,
                                 anio == 2013 ~ S22_E,
                                 anio == 2015 ~ S24_E,
                                 anio == 2016 ~ S16E,
                                 anio == 2017 ~ S17_E,
                                 anio == 2018 ~ S21.E,
                                 anio == 2020 ~ s26_d,
                                 anio == 2023 ~ S20_C,
                                 TRUE ~ NA_real_),
         bienes_telef = case_when(anio == 1998 ~ s9f,
                                  anio == 2000 ~ S10F,
                                  anio == 2001 ~ s10f,
                                  anio == 2002 ~ s10f,
                                  anio == 2003 ~ s10f,
                                  anio == 2004 ~ s10f,
                                  anio == 2005 ~ s15f,
                                  anio == 2006 ~ s15f,
                                  anio == 2007 ~ s19f,
                                  anio == 2008 ~ s19f,
                                  anio == 2009 ~ s19h,
                                  anio == 2010 ~ S21H,
                                  anio == 2011 ~ S28F,
                                  anio == 2013 ~ S22_F,
                                  anio == 2015 ~ S24_F,
                                  anio == 2016 ~ S16F,
                                  anio == 2017 ~ S17_F,
                                  anio == 2018 ~ S21.F,
                                  anio == 2020 ~ s26_e,
                                  TRUE ~ NA_real_),
         bienes_celular = case_when(anio == 2005 ~ s15g,
                                    anio == 2006 ~ s15g,
                                    anio == 2007 ~ s19g,
                                    anio == 2008 ~ s19g,
                                    anio == 2009 ~ s19i,
                                    anio == 2010 ~ S21I,
                                    anio == 2011 ~ S28G,
                                    anio == 2013 ~ S22_G,
                                    anio == 2015 ~ S24_G,
                                    anio == 2016 ~ S16G,
                                    anio == 2017 ~ S17_G,
                                    anio == 2018 ~ S21.G,
                                    anio == 2020 ~ s26_f,
                                    anio == 2023 ~ S20_D,
                                    TRUE ~ NA_real_),
         bienes_auto = case_when(anio == 1998 ~ s9g,
                                 anio == 2000 ~ S10G,
                                 anio == 2001 ~ s10g,
                                 anio == 2002 ~ s10g,
                                 anio == 2003 ~ s10g,
                                 anio == 2004 ~ s10g,
                                 anio == 2005 ~ s15h,
                                 anio == 2006 ~ s15h,
                                 anio == 2007 ~ s19h,
                                 anio == 2008 ~ s19h,
                                 anio == 2009 ~ s19j,
                                 anio == 2010 ~ S21J,
                                 anio == 2011 ~ S28H,
                                 anio == 2013 ~ S22_H,
                                 anio == 2015 ~ S24_I,
                                 anio == 2016 ~ S16I,
                                 anio == 2017 ~ S17_I,
                                 anio == 2018 ~ S21.I,
                                 anio == 2020 ~ s26_g,
                                 anio == 2023 ~ S20_E),
         bienes_cloaca = case_when(anio == 1998 ~ s9m,
                                   anio == 2000 ~ S10M,
                                   anio == 2001 ~ s10k,
                                   anio == 2002 ~ s10k,
                                   anio == 2003 ~ s10k,
                                   anio == 2004 ~ s10k,
                                   anio == 2005 ~ s15l,
                                   anio == 2006 ~ s15l,
                                   anio == 2007 ~ s19l,
                                   anio == 2008 ~ s19l,
                                   anio == 2009 ~ s19n,
                                   anio == 2010 ~ S21N,
                                   anio == 2011 ~ S28K,
                                   anio == 2013 ~ S22_K,
                                   anio == 2015 ~ S24_K,
                                   anio == 2016 ~ S16K,
                                   anio == 2017 ~ S17_K,
                                   anio == 2018 ~ S21.K,
                                   anio == 2020 ~ s26_i,
                                   anio == 2023 ~ S20_G,
                                   TRUE ~ NA_real_),
         bienes_aguapot = case_when(anio == 1998 ~ s9k,
                                    anio == 2000 ~ S10K,
                                    anio == 2001 ~ s10i,
                                    anio == 2002 ~ s10i,
                                    anio == 2003 ~ s10i,
                                    anio == 2004 ~ s10i,
                                    anio == 2005 ~ s15j,
                                    anio == 2006 ~ s15j,
                                    anio == 2007 ~ s19j,
                                    anio == 2008 ~ s19j,
                                    anio == 2009 ~ s19l,
                                    anio == 2010 ~ S21L,
                                    anio == 2011 ~ S28I,
                                    anio == 2013 ~ S22_I,
                                    anio == 2016 ~ S16M,
                                    anio == 2017 ~ S17_M,
                                    anio == 2018 ~ S21.M,
                                    anio == 2020 ~ s26_k,
                                    anio == 2023 ~ S20_I,
                                    TRUE ~ NA_real_),
         bienes_aguacal = case_when(anio == 1998 ~ s9l,
                                    anio == 2000 ~ S10L,
                                    anio == 2001 ~ s10j,
                                    anio == 2002 ~ s10j,
                                    anio == 2003 ~ s10j,
                                    anio == 2004 ~ s10j,
                                    anio == 2005 ~ s15k,
                                    anio == 2006 ~ s15k,
                                    anio == 2007 ~ s19k,
                                    anio == 2008 ~ s19k,
                                    anio == 2009 ~ s19m,
                                    anio == 2010 ~ S21M,
                                    anio == 2011 ~ S28J,
                                    anio == 2013 ~ S22_J,
                                    anio == 2015 ~ S24_J,
                                    anio == 2016 ~ S16J,
                                    anio == 2017 ~ S17_J,
                                    anio == 2018 ~ S21.J,
                                    anio == 2020 ~ s26_h,
                                    anio == 2023 ~ S20_F,
                                    TRUE ~ NA_real_),
         bienes_casa = case_when(anio == 1998 ~ s9c,
                                 anio == 2000 ~ S10C,
                                 anio == 2001 ~ s10c,
                                 anio == 2002 ~ s10c,
                                 anio == 2003 ~ s10c,
                                 anio == 2004 ~ s10c,
                                 anio == 2005 ~ s15c,
                                 anio == 2006 ~ s15c,
                                 anio == 2007 ~ s19c,
                                 anio == 2008 ~ s19c,
                                 anio == 2009 ~ s19e,
                                 anio == 2010 ~ S21E,
                                 anio == 2011 ~ S28C,
                                 anio == 2013 ~ S22_C,
                                 anio == 2015 ~ S24_B,
                                 anio == 2016 ~ S16B,
                                 anio == 2017 ~ S17_B,
                                 anio == 2018 ~ S21.B,
                                 anio == 2020 ~ s26_b,
                                 anio == 2023 ~ S20_B,
                                 TRUE ~ NA_real_),
         evasion = case_when(anio == 1998 ~ np66b,
                             anio == 2003 ~ p66stb,
                             anio == 2005 ~ p80st,
                             anio == 2008 ~ p70st,
                             anio == 2009 ~ p61st,
                             anio == 2010 ~ P57ST_A,
                             anio == 2011 ~ P71ST_A,
                             anio == 2013 ~ P58ST,
                             anio == 2015 ~ P56ST,
                             anio == 2016 ~ P24ST,
                             anio == 2023 ~ P22ST,
                             TRUE ~ NA_real_),
         arreglo_impuestos = case_when(anio == 1998 ~ np64b,
                                       anio == 2002 ~ p49stb,
                                       anio == 2007 ~ p92stb,
                                       anio == 2009 ~ p60st_b,
                                       anio == 2010 ~ P56ST,
                                       anio == 2020 ~ p24st_b,
                                       TRUE ~ NA_real_))


# Recodificación y categorías---------

seleccion_variables <- c("democracia",
                         "satisf_democracia",
                         "garantia_politica",
                         "garantia_profesion",
                         "garantia_medioambiente",
                         "garantia_propprivada",
                         "garantia_distriqueza",
                         "garantia_genero",
                         "garantia_oportunidades",
                         "garantia_expresion",
                         "garantia_religion",
                         "garantia_crimen",
                         "garantia_seguridadsocial",
                         "garantia_solidaridad",
                         "garantia_trabajo",
                         "ideologia",
                         "pais_poderosos",
                         "escala_pobriq_padres",
                         "escala_pobriq_personal",
                         "escala_pobriq_hijos",
                         "situacion_padres",
                         "situacion_hijos",
                         "just_dist_ingresos",
                         "situacion_eco_pais",
                         "ing_subjetivo",
                         "pro_mercado",
                         "bienes_comp",
                         "bienes_lava",
                         "bienes_telef",
                         "bienes_celular",
                         "bienes_auto",
                         "bienes_cloaca",
                         "bienes_aguapot",
                         "bienes_aguacal",
                         "bienes_casa",
                         "evasion",
                         "arreglo_impuestos",
                         "sexo2",
                         "edad",
                         "años_ed",
                         "estado_ocupacional",
                         "trabajo_anterior",
                         "trabajo_actual",
                         "clase_subjetiva")

for (i in seleccion_variables) {
  latinobarometro[[i]] <- ifelse(latinobarometro[[i]] < 1, NA, latinobarometro[[i]])
}
                         

latinobarometro <- latinobarometro %>% 
  mutate(sexo2 = factor(sexo2, labels = c("Varón", "Mujer")),
         nivel_ed = car::recode(años_ed,
                                "1:8=1; 9:14=2; 16=2; 15=3;17=3; c(-4, -2, 0)=NA"),
         nivel_ed = factor(nivel_ed, labels = c("Hasta prim. comp", "Hasta sec. comp",
                                                "Superior comp")),
         estado_ocupacional_f = factor(estado_ocupacional, 
                                     labels = c("Independiente/cuenta propia",
                                                "Asalariado en emp. pública",
                                                "Asalariado en emp. privada",
                                                "Temporalmente no trabaja",
                                                "Retirado/pensionado",
                                                "No trabaja",
                                                "Estudiante")),
         trabajo_anterior_f = factor(trabajo_anterior, 
                                   labels = c("Profesional autónomo",
                                              "Dueño de negocio",
                                              "Agricultor/Pescador",
                                              "Trabajador por cuenta propia, ambulante",
                                              "Profesional asalariado",
                                              "Alto ejecutivo",
                                              "Ejecutivo de mando medio",
                                              "Otro empleado")),
         trabajo_actual_f = factor(trabajo_actual, 
                                   labels = c("Profesional autónomo",
                                              "Dueño de negocio",
                                              "Agricultor/Pescador",
                                              "Trabajador por cuenta propia, ambulante",
                                              "Profesional asalariado",
                                              "Alto ejecutivo",
                                              "Ejecutivo de mando medio",
                                              "Otro empleado")),
         clase_subjetiva_f = factor(clase_subjetiva, 
                                   labels = c("Alta",
                                              "Media alta",
                                              "Media",
                                              "Media baja",
                                              "Baja")),
         democracia_f = factor(democracia,
                               labels = c("La democracia es preferible a cualquier otra forma de gobierno",
                                          "En algunas circunstancias, un gobierno autoritario puede ser preferible a uno democrático",
                                          "A la gente como uno, nos da lo mismo un régimen democrático")),
         satisf_democracia_f = factor(satisf_democracia,
                                     labels = c("Muy satisfecho",
                                                "Más bien satisfecho",
                                                "No muy satisfecho",
                                                "Nada satisfecho")),
         ideologia = ifelse(ideologia == 97, NA, ideologia),
         pais_poderosos_f = factor(pais_poderosos,
                                   labels = c("Grupos poderosos en su propio beneficio",
                                              "Para el bien de todo el pueblo")),
         just_dist_ingresos_f = factor(just_dist_ingresos,
                                       labels = c("Muy justa",
                                                  "Justa",
                                                  "Injusta",
                                                  "Muy injusta")),
         situacion_eco_pais_f = factor(situacion_eco_pais,
                                       labels = c("Muy buena",
                                                  "Buena",
                                                  "Regular",
                                                  "Mala",
                                                  "Muy mala")),
         ingreso_subjetivo_f = factor(ing_subjetivo,
                                     labels = c("Les alcanza bien, pueden ahorrar",
                                                "Les alcanza justo, sin grandes dificultades",
                                                "No les alcanza, tienen dificultades",
                                                "No les alcanza, tienen grandes dificultades")),
         pro_mercado_f = factor(pro_mercado,
                                labels = c("Muy de acuerdo",
                                           "De acuerdo",
                                           "En desacuerdo",
                                           "Muy en desacuerdo")))
         
                                      
         
variables_garantia <- c("garantia_politica",
                        "garantia_profesion",
                        "garantia_medioambiente",
                        "garantia_propprivada",
                        "garantia_distriqueza",
                        "garantia_genero",
                        "garantia_oportunidades",
                        "garantia_expresion",
                        "garantia_religion",
                        "garantia_crimen",
                        "garantia_seguridadsocial",
                        "garantia_solidaridad",
                        "garantia_trabajo")

etiquetas_garantia <- c("Completamente garantizadas",
                        "Algo garantizadas",
                        "Poco garantizadas",
                        "Para nada garantizadas")
                                     
for (i in variables_garantia) {
  nombre_factor <- paste0(i, "_f")
  latinobarometro[[nombre_factor]] <- factor(latinobarometro[[i]], labels = etiquetas_garantia)
}


#Selección de variables con las que nos quedamos---------------

orden_variables <- c("entrevista",
                     "pais",
                     "pais_f",
                     "anio",
                     "wt",
                     "sexo2",
                     "edad",
                     "nivel_ed",
                     "años_ed",
                     "estado_ocupacional_f",
                     "trabajo_anterior_f",
                     "trabajo_actual_f",
                     "clase_subjetiva_f",
                     "democracia_f",
                     "satisf_democracia_f",
                     "garantia_politica_f",
                     "garantia_profesion_f",
                     "garantia_medioambiente_f",
                     "garantia_propprivada_f",
                     "garantia_distriqueza_f",
                     "garantia_genero_f",
                     "garantia_oportunidades_f",
                     "garantia_expresion_f",
                     "garantia_religion_f",
                     "garantia_crimen_f",
                     "garantia_seguridadsocial_f",
                     "garantia_solidaridad_f",
                     "garantia_trabajo_f",
                     "ideologia",
                     "pais_poderosos_f",
                     "escala_pobriq_padres",
                     "escala_pobriq_personal",
                     "escala_pobriq_hijos",
                     "situacion_padres",
                     "situacion_hijos",
                     "just_dist_ingresos_f",
                     "situacion_eco_pais_f",
                     "ingreso_subjetivo_f",
                     "pro_mercado_f",
                     "bienes_comp",
                     "bienes_lava",
                     "bienes_telef",
                     "bienes_celular",
                     "bienes_auto",
                     "bienes_cloaca",
                     "bienes_aguapot",
                     "bienes_aguacal",
                     "bienes_casa",
                     "evasion",
                     "arreglo_impuestos")

latinobarometro <- latinobarometro %>% 
  select(all_of(orden_variables))

#Guardamos el dataset limpio-------------------
save(latinobarometro, file = "bases/latinobarometro_select.RData")

  
  
  
